### ISSUE TITLE
Doesn't work...

### ISSUE THREAD

**Issue by gbdavidx** [thomasloven/lovelace-layout-card#1]
```
resources:
  - url: /local/custom-lovelace/upcoming-media-card/upcoming-media-card.js?v=0.2.2
    type: js
  - url: /local/custom_ui/ecobee-card.js
    type: js
  - url: /local/card-modder.js
    type: module
  - url: /local/custom_ui/dark-sky-weather-card.js?v=1
    type: js
  - url: /local/custom_ui/layout-card.js
    type: ja
  - url: /local/custom_ui/button-card.js
    type: module

name: Test
views:
  - id: 0
    title: Home
    panel: True
    cards:
        - type: custom:layout-card
          cards:
            - type: entities
              title: 1
              entities:
                - remote.living_room

```
Home Assistant
0.81.6
my error is 

http://192.168.1.214:8123/local/custom_ui/layout-card.js:1:21 Uncaught SyntaxError: Unexpected identifier
