### ISSUE TITLE
The background of a Bar-card "pulses", "flashes"

### ISSUE THREAD

**Issue by Veuchez** [thomasloven/lovelace-layout-card#106]
I have inserted a bar-card that displays the status of a counter that updates every second.
If I insert this code in the card to change the style, the background of the bar "pulses" every second, so every time the counter value changes.
style: |
    ha-card {
      --ha-card-box-shadow: 'none';
    }
Is there any way to avoid it? am I doing something wrong?
Thank you!

**Comment by thomasloven** [comment]
Please try version 2.0.0.

**Comment by ntompson** [comment]
I'm seeing the same thing - I'm fairly sure it only started since upgrading to 2.0.0. In my case, it is a customisation to the inbuilt `glance` card. Whenever the sensor updates, the background colour flashes:

```yaml
      - type: glance
        entities:
          - entity: sensor.temperature_8434
            name: Kitchen
            style:  |
              :host { 
                background: 
                  {% if states(config.entity) |float <0.5 %}
                    #e6e6e6;
                  {% elif states(config.entity) |float <19.5 %}
                    #aaddff;
                  {% elif states(config.entity) |float <20.5 %}
                    #86f7ec;
                  {% elif states(config.entity) |float <23 %}
                    #aaffaa;
                  {% elif states(config.entity) |float <25 %}
                    #ffddaa;
                  {% else %}
                    #ffaaaa;
                  {% endif %}
              }
```

The flashing seems to only happen when the `glance` card is on a page with a `layout-card` defined.
