### ISSUE TITLE
Add support for grid responsive layout

### ISSUE THREAD

**Issue by martindybal** [thomasloven/lovelace-layout-card#107]
It would be nice to add options for defining grid responsive.

```yaml
grid-layouts:
  -  min-width: 1800
      gridcols: <grid_cols>
      gridrows: <grid_rows>
      gridgap: <grid_gap>
      gridplace: <grid_place>
  -  min-width: 1200
      gridcols: <grid_cols>
      gridrows: <grid_rows>
      gridgap: <grid_gap>
      gridplace: <grid_place>
```

It could be very powerful with areas #88 

@thomasloven what do you think?
