### ISSUE TITLE
Fixed height with scrollbar for vertical-stack in grid-layout

### ISSUE THREAD

**Issue by noxhirsch** [thomasloven/lovelace-layout-card#109]
Hi, I'm playing with the new layout-card v2.0 at the moment - thank you for that great update!

Is there a way to set a fixed height with `overflow-y:scroll` for vertical-stack in the grid-layout? At the moment I'm using this 'hack':

```
type: 'custom:mod-card'
card_mod:
  style: 'ha-card { height: 737px; overflow-y:scroll!important; }'
card:
  type: vertical-stack
  cards:
    - ...
    - ...
    - ...
```
While this works, there's of course no UI editor available anymore (also you recommend, not using mod-card).

This is my layout-config:
<img src="https://user-images.githubusercontent.com/30938717/111074713-90b31f00-84e4-11eb-9551-120fd8a5d057.png"  width=500 />

If that's not possible now, I'd like to propose it as a feature request for future version of layout-card. 

I'm using it for my tablet dashboards, where I have a static area with the most importand cards and a scrollable area with many less important cards.
