### ISSUE TITLE
Column_width not working with today's update

### ISSUE THREAD

**Issue by Shadowpheonix** [thomasloven/lovelace-layout-card#11]
Today's update (https://github.com/thomasloven/lovelace-layout-card/commit/25d4d4615ff46edc795d025f32a26e8950286f20) seems to have completely broken when using column_width.

This works fine...
```
  - title: Main_Test
    panel: true
    cards:
      - type: custom:layout-card
        layout: horizontal
        cards:
          - type: entities
            title: 1
            entities:
              - light.bed_light
          - type: entities
            title: 2
            entities:
              - light.bed_light
          - type: entities
            title: 3
            entities:
              - light.bed_light
```

This completely fails to load...
```
  - title: Main_Test
    panel: true
    cards:
      - type: custom:layout-card
        layout: horizontal
        column_width: 300
        cards:
          - type: entities
            title: 1
            entities:
              - light.bed_light
          - type: entities
            title: 2
            entities:
              - light.bed_light
          - type: entities
            title: 3
            entities:
              - light.bed_light
````

I have also tried ``column_width: 300px`` and ``column_width: [300px, 300px, 300px]``.

When it fails, my Home-Assistant log reports "2019-02-28 14:06:13 ERROR (MainThread) [frontend.js.latest.201902200] https://my.domain/customcards/custom-ui/layout-card.js:119:28 Uncaught TypeError: Cannot read property 'push' of undefined".

If it matters, I am running Home-Assistant v0.88.1, and I used card-updater to update to the latest build of layout-card.  Card-updater reports card-tools as current.
