### ISSUE TITLE
v2.0 breaking changes - "min_columns" option missing

### ISSUE THREAD

**Issue by bcutter** [thomasloven/lovelace-layout-card#110]
How to transform code to have cards look the same like with v16 (last release before v2.0.0)?

What I had in a view with panel mode enabled:

```
type: 'custom:mod-card'
style: |
  ha-card {
    padding: 7px;
    background: none;
  }
card:
  type: 'custom:layout-card'
  layout: horizontal
  min_columns: 2
  max_width: 100%
  cards:
    - type: 'custom:mod-card'
      style: |
        ha-card {
          height: 220px
        }
      card:
        type: button
        tap_action:
          action: navigate
          navigation_path: betriebsstatus
        name: Betriebsstatus
        icon: 'mdi:checkbox-marked-circle'
        hold_action:
          action: none
    - type: 'custom:mod-card'
      ...
      ...
```

Relevant part: with v2.0 instead of

```
  type: 'custom:layout-card'
  layout: horizontal
  min_columns: 2
  max_width: 100%
  cards:
```

I tried

```
  type: 'custom:layout-card'
  layout_type: horizontal
  layout_options:
    column: 2
    max_width: 100%
  cards:
```

but the result is not the same: now I have only ONE column on the mobile/smartphone view instead of two next to each other.

**"Breaking change" is good to know, but where´s guidance on how to fix things so everything can look the same as before the update?** I´m a bit lost...

It seems like `min_columns` does not exist anymore. **How to achieve what that did with v2.0 now?**

Look desktop with v16 release (GOOD):
![grafik](https://user-images.githubusercontent.com/13799156/111075911-64020600-84ea-11eb-87b9-bc850da0f2bf.png)

Look desktop after updating to v2.0.0 release without changing anything (BAD):
![grafik](https://user-images.githubusercontent.com/13799156/111075932-73814f00-84ea-11eb-940d-fb249aead2fb.png)

--> When making above code changes, desktop looks GOOD.

I can adjust the view so on the desktop it looks like before the update. BUT then the mobile view will break:

mobile view with v16 (GOOD):
![grafik](https://user-images.githubusercontent.com/13799156/111075981-9dd30c80-84ea-11eb-99b5-d126bc71a1f8.png)

mobile view with v2.0.0 *after* applying some code changes (BAD):
![grafik](https://user-images.githubusercontent.com/13799156/111076140-61ec7700-84eb-11eb-9dcd-e10e3cd36f22.png)

**--> When making above changes, mobile is broken (missing 2 columns setup).**

I always need to balance the UI to have it look good on the desktop and the mobile view at the same time. With v16 this was possible. With v2.0.0 I see no way to achieve the same.

**Comment by bcutter** [comment]
After trying and testing like crazy for another hour, I needed to revert back to v16 release. It´s just impossible!

How can you release updates that don´t offer the same possibilities as earlier releases? `min_columns` option is missing!

Help urgently needed @thomasloven.

**Comment by VDRainer** [comment]
I'm also missing some examples for the yaml mode users.
I have this view:
```
  - title: MCP2HA-GW
    path: mcp2ha_gw
    icon: mdi:raspberry-pi
    panel: true
    cards:

      - type: custom:layout-card
        layout: vertical
        max_columns: 3
        cards:

          - type: entities
            title: MCP2HA Gateway
            show_header_toggle: false
            state_color: true
            entities:
              - entity: some.entity
                ...

          - break

          - type: entities
            title: Beaglebone
            show_header_toggle: false
            state_color: true
              - entity: some.entity
                ...

          - break

          - type: entities
            title: Beaglebone
            show_header_toggle: false
            state_color: true
              - entity: some.entity
                ...
```
How to transfer to 2.0?
Is the panel mode for the view obsolete?

**Comment by thomasloven** [comment]
As is industry practice when something is named "2.0" you should expect it to be more or less a new product and require set up from the ground up.

If you don't like that, you're - as always - free to not upgrade.

The setting you're looking for is `width`, as in "A number of evenly sized columns is prepared based on available space, the `width` option and the `max_cols` option."

The screen is divided into columns that are at least `width` pixels wide. If your screen cannot fit two times that width, you'll only get one column.

**Comment by bcutter** [comment]
I saw the release notes have been enhanced to contain a big warning, that´s good.

I meanwhile tested 2,5 hours to get the same result with > v2.0 as before, but still no chance. Ah would be great to have a simple converter "You used this and that, now you have to use this and that to get the same result". Still a one way road for me, always turning back to version 16.

I don´t get it. The stuff I used layout-card before is not that special.

**Comment by thomasloven** [comment]
Again, the option you're looking for is `width`, as in:


> Option | Values | Description | Default
> -- | -- | -- | --
> width | number | Size in pixels of each column | 300

**Comment by Jpsy** [comment]
@bcutter I understand your frustration. #metoo I had to invest quite some time to get my layouts converted.
But please understand that all this is voluntary work. And every decent programmer in the world will tell you that redesign and  reengineering are a normal part of any software evolution.
The fact that you are not spoon fed on how to handle breaking changes is the simple result of the limited time that each contributor can invest. Again: This is all voluntary and free, private time that is provided here for you. Have you seen how many contributions Thomas has provided for the community? Have a look [here](https://github.com/thomasloven). Over 500 commits to public projects over the last year alone. Approx 2 per day. Any further questions? I hope not. If this is not good enough for you, you have to pay for a professional product. And even then you are not guaranteed to be supported over a longer time (as several commercial home automation products have proven over the last years).
Sorry for being blunt.

**Comment by bcutter** [comment]
@Jpsy: I totally get you. I have great respect for all the contributions made by Thomas. I can´t imagine running HA without all the integrations from him I use from the very beginning.

I meanwhile could track down my specific issue to the missing `min_columns` option which seems to has been removed after version 16. Without this option I see no way to fix the layout after updating so my lovelace panel mode dashboards look the same like before.

So @thomasloven my questions are:
1) Has `min_columns` setting been removed?
2) How to achieve the same without it?

I simply have no idea how to specify the issue even more precise than I did. I´m not sure if it´s me not understanding the width option or if it´s you not understanding the issue.

I tested the width option you noticed twice (from 0, 100, 200, 300 to 500), but that did not make any difference. Even with `width: 50` there´s no second column created on the mobile view.

Before / v16:
```
card:
  type: 'custom:layout-card'
  layout: horizontal
  min_columns: 2
  max_width: 100%
  cards:
  ...
```

After / v2.2.3:
```
card:
  type: 'custom:layout-card'
  layout_type: 'custom:horizontal-layout'
  layout:
    width: 0
    max_cols: 0
    min_columns: 2 # <-- not respected  (!!!) Might be root cause!
  cards:
  ...
```
```

While with those simple changes everything looks the same on the desktop view (large screens), on the mobile I still get https://user-images.githubusercontent.com/13799156/111076140-61ec7700-84eb-11eb-9dcd-e10e3cd36f22.png
