### ISSUE TITLE
possible issue with cast  on version 2.0

### ISSUE THREAD

**Issue by scooper1** [thomasloven/lovelace-layout-card#112]
i am having problems with grid view  when casting to a google hub or problerly to any other device
the grid options are totally ignored when a lovelace view is cast using dash cast  - EDIT -  it just the google hubs  - any idea of how to work around this ?   --- edit  Third time around installing  seams to be working as 1.6 but hacs says 2.1  - putting up new issue for this problem as looks like a bad update by hacs
but ok when view with chrome browser
this is new behaviour
i suspect i am doing something wrong 

puting grid-rows etc the dash just breaks both view
trying  type: custom:grid-layout   with and without quotes says card not available - i am running 2.1 and done reboot and hard reload

```
views:
  - path: Home
    title: gogle mini hub
    background: center / cover no-repeat fixed url('/local/black.jpg')
    panel: true
    icon: 'mdi:home'
    theme: ''
    badges: []
    cards:
      - type: 'custom:layout-card'
        layout: grid
        gridrows: 50
        gridcols: 40
        gridgap: 1px
        cards:
          - entity: binary_sensor.updater
            template: updater
            gridrow: 10 / 12
            gridcol: 3 / 4
            type: 'custom:button-card'
          - entity: sensor.current_consumption_w
            template: power1
            gridrow: 10 / 12
            gridcol: 9 / 10
            type: 'custom:button-card'
          - entity: sensor.car_current_consumption_w
            template: power_car
            gridrow: 10 / 12
            gridcol: 10 / 11
            type: 'custom:button-card'
          - entity: sensor.hacs
            template: hacs
            type: 'custom:button-card'
            gridrow: 10 / 12
            gridcol: 4 / 5
          - entity: sensor.skippy_battery_level
            template: skippy
            gridrow: 10 / 12
            gridcol: 8 / 9
            type: 'custom:button-card'
          - entity: binary_sensor.car_ping
            template: car_ping
            gridrow: 10 / 12
            gridcol: 6 / 7
            type: 'custom:button-card'
          - entity: switch.boiling_water_heater
            template: boiler
            gridrow: 10 / 12
            gridcol: 7 / 8
            type: 'custom:button-card'
          - entity: light.shelly_shdm_1_d172a2
            template: light
            gridrow: 6 / 8
            gridcol: 5 / 6
            type: 'custom:button-card'
          - entity: light.shelly_shdm_1_d3e303
            template: light
            gridrow: 6 / 8
            gridcol: 7 / 8
            type: 'custom:button-card'
          - entity: light.virtual_kitchen_lights
            template: light
            gridrow: 6 / 8
            gridcol: 6 / 7
            type: 'custom:button-card'
          - entity: light.front_room_main
            template: light
            gridrow: 6 / 8
            gridcol: 1 / 2
            type: 'custom:button-card'
          - entity: light.front_room_night
            template: light
            gridrow: 6 / 8
            gridcol: 2 / 3
            type: 'custom:button-card'
          - entity: light.back_room_main
            template: light
            gridrow: 6 / 8
            gridcol: 3 / 5
            type: 'custom:button-card'
          - entity: light.back_room_night
            template: light
            gridrow: 6 / 8
            gridcol: 4 / 5
            type: 'custom:button-card'
          - entity: cover.blind_front_room
            template: blind
            name: Front Room
            gridrow: 4 / 6
            gridcol: 1 / 2
            type: 'custom:button-card'
          - entity: cover.blind_kitchen
            name: Kitchen
            template: blind
            gridrow: 4 / 6
            gridcol: 2 / 3
            type: 'custom:button-card'
          - entity: cover.blind_back_bedroom
            name: Back Bedroom
            template: blind
            gridrow: 4 / 6
            gridcol: 3 / 4
            type: 'custom:button-card'
          - entity: cover.blind_front_bedroom
            template: blind
            name: Front Bedroom
            gridrow: 4 / 6
            gridcol: 4 / 5
            type: 'custom:button-card'
          - entity: cover.blind_box_bedroom
            template: blind
            name: Box Bedroom
            gridrow: 4 / 6
            gridcol: 5 / 6
            type: 'custom:button-card'
          - entity: cover.blind_top_floor_1
            name: Top Floor Back
            template: blind
            gridrow: 4 / 6
            gridcol: 6 / 7
            type: 'custom:button-card'
          - entity: cover.blind_top_floor_2
            name: Top Floor Front
            template: blind
            gridrow: 4 / 6
            gridcol: 7 / 8
            type: 'custom:button-card'
          - entity: cover.blind_top_floor_bathroom
            name: Top Bathroom
            template: blind
            gridrow: 4 / 6
            gridcol: 8 / 9
            type: 'custom:button-card'
          - entity: switch.wiser_cooling_fan
            template: fan
            name: Cooling Fan
            gridrow: 10 / 12
            gridcol: 5 / 6
            type: 'custom:button-card'
          - entity: climate.wiser_back_room
            template: wiser
            gridrow: 1 / 4
            gridcol: 1 / 2
            type: 'custom:button-card'
          - entity: climate.wiser_front_room
            gridrow: 1 / 4
            gridcol: 2 / 3
            template: wiser
            type: 'custom:button-card'
          - entity: climate.wiser_hall
            template: wiser
            gridrow: 1 / 4
            gridcol: 3 / 4
            type: 'custom:button-card'
          - entity: climate.wiser_old_kitchen
            template: wiser
            gridrow: 1 / 4
            gridcol: 4 / 5
            type: 'custom:button-card'
          - entity: climate.wiser_mum_bedroom
            template: wiser
            gridrow: 1 / 4
            gridcol: 5 / 6
            type: 'custom:button-card'
          - entity: climate.wiser_back_bedroom
            template: wiser
            gridrow: 1 / 4
            gridcol: 6 / 7
            type: 'custom:button-card'
          - entity: climate.wiser_mums_bath_room
            template: wiser
            gridrow: 1 / 4
            gridcol: 7 / 8
            type: 'custom:button-card'
          - entity: climate.wiser_middle_toilet
            template: wiser
            gridrow: 1 / 4
            gridcol: 8 / 9
            type: 'custom:button-card'
          - entity: climate.wiser_top_bath_room
            template: wiser
            gridrow: 1 / 4
            gridcol: 9 / 10
            type: 'custom:button-card'
          - entity: climate.wiser_top_floor
            template: wiser
            gridrow: 1 / 4
            gridcol: 10 / 11
            type: 'custom:button-card'
          - entity: sensor.outdoor_temperature
            template: temp
            type: 'custom:button-card'
            gridrow: 8 / 10
            gridcol: 1 / 2
          - entity: sensor.rain_rate_2
            template: rain_r
            gridrow: 8 / 10
            gridcol: 2 / 3
            type: 'custom:button-card'
          - entity: sensor.daily_rain_rate_2
            template: rain_d
            gridrow: 8 / 10
            gridcol: 3 / 4
            type: 'custom:button-card'
          - entity: sensor.wind_gust
            template: wind
            gridrow: 8 / 10
            gridcol: 4 / 5
            type: 'custom:button-card'
          - entity: sensor.humidity
            template: weather
            icon: 'mdi:water-percent'
            name: Humidity
            gridrow: 8 / 10
            gridcol: 5 / 6
            type: 'custom:button-card'
          - entity: camera.back
            template: camera
            show_live_stream: true
            gridrow: 4 / 7
            gridcol: 9 / 11
            type: 'custom:button-card'
          - entity: camera.front_cam2
            template: camera
            gridrow: 7 / 10
            gridcol: 9 / 11
            type: 'custom:button-card'
          - entity: sensor.time
            template: standard
            group_expand: false
            show_state: true
            show_icon: false
            show_label: false
            show_last_changed: false
            show_name: false
            show_live_stream: true
            styles:
              card:
                - width: 250px
                - height: 100px
                - border: 0px solid black
              state:
                - color: '#00FF00'
                - justify-self: left
                - font-size: 80px
            type: 'custom:button-card'
            style: |
              ha-card {
              margin: 0 0;
              width: 250px;
              Hight: 75px
              padding: 0 0 0 0;
              padding-top: 0;

              background: none;
              box-shadow: none;
              }
            gridrow: 10 / 12
            gridcol: 1 / 4

```
