### ISSUE TITLE
2.1.0 - max_width does not function

### ISSUE THREAD

**Issue by matejdro** [thomasloven/lovelace-layout-card#114]
I have installed new version of the Layout card. My goal is to replicate this setup from old layout card where every column was exactly 300 px wide:

```
type: 'custom:layout-card'
layout: horizontal
column_width: 300px
```

From what I see, this should work with the new layout card:

```
type: 'custom:horizontal-layout'
layout:
  width: 300
  max_width: 300
```

However, max_width does not appear to work. Card will generate 3 very wide columns (around 450px each):

![image](https://user-images.githubusercontent.com/507922/111108178-9b0f0080-8558-11eb-94b0-e64ca2a075c6.png)
