### ISSUE TITLE
custom:grid-layout not working in browser_mod.popup

### ISSUE THREAD

**Issue by sickidolderivative** [thomasloven/lovelace-layout-card#116]
Good morning

I cannot get the custom:grid-layout work in a browser_mod.popup. It works fine as a separate view. Here's a minimum setup to reproduce the problem in developer tools:

```
service: browser_mod.popup
data:
  title: Popup example
  hide_header: true
  auto_close: true
  large: true
  deviceID:
    - dashboard
  card:
    type: custom:grid-layout
    layout:
      grid-template-columns: 30% 70%
      grid-template-rows: auto
      grid-template-areas: |
        "a b"
    cards:
      - type: entities
        entities:
          - sun.sun
        layout:
          grid-area: a
      - type: entities
        entities:
          - sun.sun
        layout:
          grid-area: b
```

 I'd appreciate any help.

**Comment by NinDTendo** [comment]
This problem is unrealted to Layout-Card

I am not entirely sure, but the service call "browser_mod.popup" is not working anymore. It was something with fire dom event.

this is how I did mine:
```
action: fire-dom-event
browser_mod:
  command: popup
  title: Information
  hide_header: true
  deviceID: this
[...]
```

check out [this](https://github.com/thomasloven/hass-browser_mod/issues/194) for more information
