### ISSUE TITLE
Grid - Not working in card layout

### ISSUE THREAD

**Issue by mafelipe16** [thomasloven/lovelace-layout-card#120]
Im trying to start using Grid layout, but.only inside the view. Im doing tests but grid is not working, if I change to horizontal works perfect. Also im lacking the options to be used, I know are all the one starting with grid- from the CSS, but probably some examples with all of them used....

```
type: 'custom:layout-card'
layout: grid
grid-template-columns: 40px 50px auto 50px 40px
grid-template-rows: 25% 100px auto
cards:
  - type: 'custom:tesla-style-solar-power-card'
    grid-column: 1 / span 2
    grid-row: 1 / 1
```
