### ISSUE TITLE
[Feature request] - Extend Card visibility with show or not if sidebar is  shown or hidden

### ISSUE THREAD

**Issue by bratanon** [thomasloven/lovelace-layout-card#121]
Something like this

```
- type: markdown
  content: |
    This is only shown when the sidebar is shown
  layout:
    show:
      sidebar: shown
```

```
- type: markdown
  content: |
    This is only shown when the sidebar is hidden
  layout:
    show:
      sidebar: hidden
```
