### ISSUE TITLE
Usage in vertical layout of 'custom:layout-break' card in yaml  is unclear or isn't working

### ISSUE THREAD

**Issue by bturrie** [thomasloven/lovelace-layout-card#125]
The following yaml:
```
 - type: 'custom:layout-card'
        layout: veritcal
        cards:
          - type: 'custom:analog-clock'
            diameter: 200
            hide_SecondHand: true
            hide_FaceDigits: true
            color_HourHand: yellow
            color_MinuteHand: yellow
            color_background: gray  
			
          - type: custom:layout-break
		  
          - type: grid
            columns: 4
            cards:
```
Shows the grid card directly below the clock. Either I'm using the layout-break wrong or it isn't working from yaml
