### ISSUE TITLE
View Layout Grid - Differences between v2.1.1 and v2.2

### ISSUE THREAD

**Issue by woodmj74** [thomasloven/lovelace-layout-card#126]
My Home Assistant version: 2021.3.4

Layout-card version (FROM BROWSER CONSOLE): v2.2 (and tested in v2.1.1)

What I am doing:

Using the Grid Layout at view level, the alignment of grid-cells has changed between v2.1.1 and v2.2. In the earlier version the grid cells were distributed from a central alignment, in v2.2 this has moved to a left alignment.

Happy to accept this is now expected behaviour but reporting as it has changed between minor versions within v2.

What I expected to happen:

The layout behaviour to be common between the two versions. Screen shot of v2.1.1:
![image](https://user-images.githubusercontent.com/68328701/111758658-aafa4d80-8894-11eb-9bbd-0519c400d600.png)

What happened instead:

The alignment of the grid cells moved to the left. Screen shot of v2.2 (with necessary YAML revisions made):
![image](https://user-images.githubusercontent.com/68328701/111759856-fb25df80-8895-11eb-935b-d24117bb6e15.png)

**Minimal** steps to reproduce:

View configuration - common between v2.1.1 and v2.2:
```
    panel: false
    type: 'custom:grid-layout'
    layout:
      grid-template-columns: 30% 30% 30%
      grid-template-rows: 10px auto
      grid-template-areas: |
        ". . ."
        "p11 p12 p13"
        "p21 p21 p23"
        "p31 p32 p33"
      mediaquery:
        '(max-width: 800px)':
          grid-template-columns: 95%
          grid-template-areas: |
            "p11"
            "p12"
            "p13"
            "p21"
            "p22"
            "p23"
            "p31"
            "p32"
            "p33"
```
Sample card configuration in v2.1.1:
```
type: 'custom:mini-graph-card'
name: Temperature
entities:
  - entity: sensor.lounge_temperature
  - entity: sensor.landing_temperature
  - entity: sensor.roof_temperature
show:
  state: false
  fill: false
layout:
  grid-area: p21
style: |
  ha-card {
    opacity: 80%
  }
```
The same card configured in v2.2:
```
type: 'custom:mini-graph-card'
name: Temperature
entities:
  - entity: sensor.lounge_temperature
  - entity: sensor.landing_temperature
  - entity: sensor.roof_temperature
show:
  state: false
  fill: false
view_layout:
  grid-area: p21
style: |
  ha-card {
    opacity: 80%
  }

```

Error messages from the browser console:

Seen in both v2.1.1 and  v2.2:
```
layout-card.js:40 Uncaught (in promise) TypeError: Cannot read property 'style' of null
    at HTMLElement._setGridStyles (:8123/hacsfiles/lovelace-layout-card/layout-card.js:40)
    at HTMLElement.setConfig (:8123/hacsfiles/lovelace-layout-card/layout-card.js:40)
```
---

**By putting an X in the boxes ([X]) below, I indicate that I:**

- [X] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).
- [X] Have made sure I am using the latest version of the plugin.
- [X] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.
- [X] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
