### ISSUE TITLE
custom:grid-layout doesn't work with android app

### ISSUE THREAD

**Issue by roma777roma** [thomasloven/lovelace-layout-card#133]
My Home Assistant version: 2021.04.3

Layout-card version (FROM BROWSER CONSOLE): 2.2.3

What I am doing: Using the type: 'custom:grid-layout' and the android companion app. 

What I expected to happen: it worked fine before I expected it to continue to work

What happened instead: the error appears on the phone: "custom element doesn't exist: grid-layout" The screen is all red and nothing is visible 

**Minimal** steps to reproduce:

```yaml
  - title: test
    path: test
    type: 'custom:grid-layout'
    panel: false
    layout:
      max_cols: 5
      grid-template-columns: 190px 190px 190px 90px 90px
      grid-template-rows: 70px 70px 70px 70px 70px 70px 70px 70px 70px 70px
    badges: []
    cards:
      - type: entities
        entities:
          - light.d806c5eb_e18aa5d7
        view_layout:
          grid-column: 2 / 3
          grid-row: 1 / 2
```

Error messages from the browser console: 

---

**By putting an X in the boxes ([X]) below, I indicate that I:**

- [x] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).
- [x] Have made sure I am using the latest version of the plugin.
- [x] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.
- [x] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
