### ISSUE TITLE
Custom element doesn´t exist: Layout-card

### ISSUE THREAD

**Issue by kajmaj** [thomasloven/lovelace-layout-card#14]
I have following ui-lovelace.yaml:
```
resources:
  - url: /local/lovelace/mini-graph-card-bundle.js?v=0.3.0
    type: module
  - url: /local/lovelace/card-tools.js
    type: js
  - url: /local/lovelace/layout-card.js
    type: js 
  - url: /local/custom-lovelace/weather-card.js
.
.
title: "Home"
views:
- title: "Main"
  icon: mdi:home
  panel: true
  cards:
  - type: custom:layout-card
    cards:
    - type: vertical-stack
      cards:
      - type: glance        

```
But it seems to be not working (error message with a red background) and following log:

`2019-03-15 08:32:49 ERROR (MainThread) [frontend.js.latest.201903051] https://hassio.local:8123/local/lovelace/layout-card.js:7:1 Uncaught SyntaxError: Unexpected token <`

Did I sthg wrong?
