### ISSUE TITLE
grid-view not being respected

### ISSUE THREAD

**Issue by omayhemo** [thomasloven/lovelace-layout-card#140]
My Home Assistant version: 2021.4.4

Layout-card version 2.2.3 (HACS):

What I am doing:
Trying to use grid-views responsively.

What I expected to happen:
I expect a card with the grid-view attribute to go to the defined grid column of the same name.

What happened instead:
It goes where-ever it feels like?

**Minimal** steps to reproduce:
```
  - panel: true
    layout:
      grid-template-columns: auto 30px 25%
      grid-template-rows: auto
      grid-template-areas: |
        "header header header"
        "main . sidebar"
      mediaquery:
        "(max-width: 600px)":
          grid-template-columns: 100%
          grid-template-areas: |
            "header"
            "sidebar"
            "main"
        "(max-width: 800px)":
          grid-template-columns: 50% 50%
          grid-template-areas: |
            "header sidebar"
            "main main"
    badges: []
    cards:
      - type: 'custom:layout-card'
        layout_type: grid
        layout: {}
        cards:
          - type: markdown
            content: >
              # Dummy 1
            view_layout:
              grid-view: header
          - type: markdown
            content: >
              # Dummy 2 
            view_layout:
              grid-view: main
          - type: markdown
            content: >
              # Dummy 3 
            view_layout:
              grid-view: sidebar
        view_layout: {}
```

Results at 800px (or so):
![image](https://user-images.githubusercontent.com/2934415/114597951-f830cb80-9c56-11eb-9390-8b665bf654c5.png)

Error messages from the browser console:
None
---

**By putting an X in the boxes ([X]) below, I indicate that I:**

- [X] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).
- [X] Have made sure I am using the latest version of the plugin. **As is available in HACS**
- [X] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.
- [X] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
