### ISSUE TITLE
view_layout option not accepted by custom card

### ISSUE THREAD

**Issue by hk-ret** [thomasloven/lovelace-layout-card#141]
My Home Assistant version: 2021.4.5

Layout-card version (FROM BROWSER CONSOLE): 2.2.3

What I am doing:
Arrange cards on a view using grid-type layout. I'm trying to position the individual cards by adding `view_layout:` options to the cards. Some of the cards are of the custom type `apexcharts-card`.

What I expected to happen:
Cards to be rendered accordingly.

What happened instead:
The cards are positioned as expected. however for the `apexcharts-card`s I get a red box saying:
```
/// apexcharts-card version 1.8.2 /// value.view_layout is extraneous

type: 'custom:apexcharts-card'
view_layout:
  grid-area: main
```

**Minimal** steps to reproduce:

View:
```
    layout:
      grid-template-columns: auto
      grid-template-rows: auto
      grid-template-areas: |
        "main"
    cards:
      - type: 'custom:apexcharts-card'
        view_layout:
          grid-area: main
......
```

Error messages from the browser console:
I could not identify any error in the console relating to this issue.

---

**By putting an X in the boxes ([X]) below, I indicate that I:**

- [X] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).
- [X] Have made sure I am using the latest version of the plugin.
- [X] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.
- [X] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
