### ISSUE TITLE
Layout-card behavior is inconsistent

### ISSUE THREAD

**Issue by kamtschatka** [thomasloven/lovelace-layout-card#145]
What I am doing:

I have created a card like this:
```
type: 'custom:layout-card'
cards:
  - type: entities
    entities:
      - entity: postag.1023060501090050840400
      - type: attribute
        attribute: Latest_Country
        entity: postag.1023060501090050840400
      - postag.1025822102523050240406
      - type: attribute
        attribute: Latest_Country
        entity: postag.1025822102523050240406
layout_type: masonry
```

This results in a card like this:
![image](https://user-images.githubusercontent.com/22147234/118888561-1a73d400-b8fc-11eb-92b2-0083f117c28c.png)

Then there is a description to use the card with auto-entities https://github.com/thomasloven/lovelace-layout-card#use-with-entity-filters:
```
type: 'custom:auto-entities'
card:
  type: 'custom:layout-card'
  cards: 
    type: entities
    entities:
      - entity: postag.1023060501090050840400
      - type: attribute
        attribute: Latest_Country
        entity: postag.1023060501090050840400
      - postag.1025822102523050240406
      - type: attribute
        attribute: Latest_Country
        entity: postag.1025822102523050240406
filter:
  include:
    - entity_id: postag.1025822102523050240406
    - entity_id: postag.1023060501090050840400

```

That results in this:

![image](https://user-images.githubusercontent.com/22147234/118888576-1fd11e80-b8fc-11eb-8271-43fe783c808b.png)

So the cards parameter is completely ignored and it is defaulted to the entity card.
This is very counter intuitive as the layout-card is usually way more powerful.

The reason for this is that if the entities properties is set, this is mapped and the type is defaulted to „entity“ if it is missing: https://github.com/thomasloven/lovelace-layout-card/blob/master/src/layout-card.ts#L19

My suggestion to fix that problem would be to create a copy of the cards property instead of the entities. This will open a different problem, because naturally people will want to automatically create cards for different entities and each card shows detailed information about this entity. With my second example I would be referencing fixed entities for each card that is created, which is quite useless. So I have created a local patch that will copy the cards and provide the placeholder „+++entitiyid+++“, that will be populated by the layout-card with the current entityid and can then used in every card below it.
So the yaml for the sample above would look like this:
```
type: 'custom:auto-entities'
card:
  type: 'custom:layout-card'
  cards:
    type: entities
    entities:
      - +++entityid+++
      - type: attribute
        attribute: Latest_Country
        entity: +++entityid+++
      - +++entityid+++
      - type: attribute
        attribute: Latest_Country
        entity: +++entityid+++
filter:
  include:
    - entity_id: postag.1025822102523050240406
    - entity_id: postag.1023060501090050840400

```

The result is the following:
![image](https://user-images.githubusercontent.com/22147234/118888597-26f82c80-b8fc-11eb-9feb-96ae5b912711.png)

While I can see why it works like it works, I don't think it is how it should work. What do you think?

**Comment by sdrapha** [comment]
Hey, I was just passing by, looking for something else, but I thought I could try to help somehow..:

Did you tryed something like this I quickly put together? :   ( I did NOT tested it) 
I use something similar for multiple 'mini-media-players' cards to show multiple chromecast players instances.

```yaml
type: 'custom:auto-entities'
card:
  type: 'custom:layout-card'
card_param: cards
filter:
  include:
    - entity_id: postag.*
      options:
        type: entities
        entities:
          - entity: this.entity_id
          - entity: this.entity_id
            type: attribute
            attribute: Latest_Country
```

**Comment by kamtschatka** [comment]
Hi

Thanks for thee comment. I was also playing around a bit today for a System Monitoring dashboard and after some debugging came to a similar solution. I have not tried it with this problem yet, but I think you are correct and it might work.
One downside I see is that the "options" only apply to the current section.
This works fine:
```
    - entity_id: postag.*
      options:
        type: entities
        entities:
          - entity: this.entity_id
          - entity: this.entity_id
            type: attribute
            attribute: Latest_Country
```
This will require me to duplicate the options, as they only apply to "something else":
```
    - entity_id: <something>
    - entity_id: <something else>
      options:
        type: entities
        entities:
          - entity: this.entity_id
          - entity: this.entity_id
            type: attribute
            attribute: Latest_Country
```

I would also argue that it is quite counterintuitive that you can specify the card, but it doesn't actually work.
Since I found out that theree already is a placeholder "this.entity_id", I will change my implementation to use this as well and make it available.
