### ISSUE TITLE
swipe-card in layout-card does not update its size

### ISSUE THREAD

**Issue by matt8707** [thomasloven/lovelace-layout-card#147]
My Home Assistant version: 2021.5.5

Layout-card version (FROM BROWSER CONSOLE): 2.2.3

What I am doing: 
Using [swipe-card](https://github.com/bramkragten/swipe-card) in custom:grid-layout.

What I expected to happen: The swipe card should update its size to fit the grid

What happened instead: The swipe card only updates its size if the window is resized, looks like `this.swiper.update();` is called. The thing is, in regular lovelace it updates its size, but using custom:masonry-layout it does not so I'm unsure if it's related to swipe-card or layout-card.

related https://github.com/bramkragten/swipe-card/issues/32 

**Minimal** steps to reproduce:

```yaml
views:
  - type: custom:grid-layout
    path: 0
    layout:
      grid-template-columns: 1fr 1fr
      grid-template-rows: 1fr
      grid-template-areas: |
        "one two"
    cards:
      - type: grid #grid needed as container?
        view_layout:
          grid-area: one
        columns: 1
        cards:
          - type: custom:swipe-card
            view_layout:
              grid-area: one
            cards:
              - type: picture
                image: 'https://demo.home-assistant.io/stub_config/t-shirt-promo.png'
              - type: entities
                entities:
                  - light.x
      - type: picture
        view_layout:
          grid-area: two
        image: 'https://demo.home-assistant.io/stub_config/t-shirt-promo.png'
```

Error messages from the browser console: None

---

**By putting an X in the boxes ([X]) below, I indicate that I:**

- [x] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).
- [x] Have made sure I am using the latest version of the plugin.
- [x] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.
- [x] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
