### ISSUE TITLE
Entity filter inside Layout-card does not "disappear"

### ISSUE THREAD

**Issue by zucram** [thomasloven/lovelace-layout-card#159]
My Home Assistant version: 2021.8.5

Layout-card version (FROM BROWSER CONSOLE):
LAYOUT-CARD 2.3.0 IS INSTALLED 

What I am doing:
I have a horizontal layout card inside of a grid with a state_filter inside it. When the condition isn't met the state filter card disappears but there's a gap in-between the rest of the cards where it should have been. 

What I expected to happen:
I expected the other cards after the state filter card to cascade to the left. 

What happened instead:
There's a gap in place of the state filter card. 

**Minimal** steps to reproduce:

```yaml
# The least ammount of code possible to reproduce my error
type: custom:layout-card
cards:
  - type: glance
    entities:
      - entity: alarm_control_panel.alarm
    show_name: false
  - type: glance
    entities:
      - entity: lock.yale
    show_name: false
  - type: entity-filter
    card:
      type: glance
      show_name: false
    entities:
      - entity: binary_sensor.altanndorr_kontaktalarm
    state_filter:
      - 'on'
    show_empty: false
  - type: glance
    entities:
      - entity: sensor.entre
        icon: mdi:door
    show_name: false
  - type: glance
    entities:
      - entity: sensor.vardagsrum
        icon: mdi:sofa
    show_name: false
  - type: glance
    entities:
      - entity: sensor.overvaning
        icon: mdi:stairs-up
    show_name: false
  - type: glance
    entities:
      - entity: sensor.livingroom_average
        icon: mdi:television-classic
    show_name: false
  - type: glance
    entities:
      - entity: sensor.vinkallare_temperatur
        icon: mdi:bottle-wine
    show_name: false
layout_type: horizontal
layout:
  width: 100
  max_cols: 13
view_layout:
  grid-area: info

# End of code
```

Error messages from the browser console:
No errors
---

**By putting an X in the boxes ([X]) below, I indicate that I:**

- [x] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).
- [x] Have made sure I am using the latest version of the plugin.
- [x] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.
- [x] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
