### ISSUE TITLE
layout_card mediaquery not activating within browser_mod popup 

### ISSUE THREAD

**Issue by MadMaxMcKinney** [thomasloven/lovelace-layout-card#163]
I have a simple layout_card that I've used in other parts of my dashboard, shown below:

```yaml
    type: custom:layout-card
    layout_type: grid
    layout:
      grid-template-columns: repeat(auto-fill, minmax(115px, 160px))
      grid-template-rows: auto
      grid-gap: 8px
      mediaquery:
      "(max-width: 450px)":
        grid-template-columns: 1fr 1fr 1fr
```

However when I use this card inside a browser_mod popup the mediaquery doesn't activate. I am also using [decluttering_card](https://github.com/custom-cards/decluttering-card) to template many of my cards, which is what I'm suspecting is causing this. 

Here's my trigger for the popup as well:

```yaml
      - tap_action: 
          action: fire-dom-event
          browser_mod:
            command: popup
            title: Lights
            large: true
            style: |
              .content {
                margin: 0 !important;
              }
            card:
              !include /config/lovelace/views/subviews/subview_popup_lights.yaml
```

Any other workarounds or thoughts?
