### ISSUE TITLE
Cards not appearing - what' am I doing wrong?

### ISSUE THREAD

**Issue by selmaohneh** [thomasloven/lovelace-layout-card#169]
Hi!

Just want to get started with lovelace-layout-card. I try to set up a basic simple example by following the documentation on the README. This is my sample:

![image](https://user-images.githubusercontent.com/29881939/143761409-140f559d-7438-4918-a966-4b97c6210378.png)

But when I look at my dashboard, the whole tab stays empty.

![image](https://user-images.githubusercontent.com/29881939/143761869-5e032c5c-de59-431e-8cd6-084d451dcc54.png)

I can't see what I am doing wrong. Any ideas?

Thanks in advance!

**Comment by selmaohneh** [comment]
> Try removing "panel: true".
> 
> I found this as well. Like me, you using the Grid layout as the outermost / parent card so I don't think the panel attribute is needed.

I just tried that, nothing changed. :-/

**Comment by tgallacher** [comment]
Huh. 

Just did some checking and I can replicate this. There seems to be a bug here, as the Grid component doesn't have any children when it is set as the parent card within a panel view. 

I've found a workaround though, using the [custom layout](https://github.com/thomasloven/lovelace-layout-card#layout-card-1) card variant in this package. So, you just need to tweak what you have above to something like:

```yaml
- title: Tests
  path: testi
  type: panel
  cards:
    - type: custom:layout-card
      layout_type: custom:grid-layout
      layout:
        ...
      cards:
        ...
```

Hope that helps / works for you

**Comment by tgallacher** [comment]
Possibly related, but this has actually allowed me to fix a similar issue I was having with no cards appearing 💪 . 

In my simple case, I had a `custom:horizontal-layout` card nested within a `custom:grid-layout` card and none of the child cards were being rendered at all. 

Example:

```yaml
- type: custom:grid-layout
  layout:
    ...
  cards:
    - type: markdown
      view_layout:
        grid-area: ...
      content: >-
        Hello

    - type:  custom:horizontal-layout
      view_layout:
        grid-area: ...
      layout:
        ...
      cards:
        ...
```

To get the cards rendering, I need to change this to the above workaround:

```yaml
- type: custom:grid-layout
  layout:
    ...
  cards:
    - type: markdown
      view_layout:
        grid-area: ...
      content: >-
        Hello

    - type:  custom:layout-card
      layout_type: custom:horizontal-layout
      view_layout:
        grid-area: ...
      layout:
        ...
      cards:
        ...
```

and hey-presto, everything works.
