### ISSUE TITLE
Only one column of cards is displayed

### ISSUE THREAD

**Issue by bieniu** [thomasloven/lovelace-layout-card#17]
Often (not always) only one column of cards is displayed when I switch between views. I must then refresh the page or turn on the HA sidebar for a moment or switch view so that the number of columns returns to normal. I have cleaned the browser cache many times. Any solution for that?

HA: 0.89.2
layout-card: 226f86
browser: Chrome/Opera/Firefox

Incorrect view with one column:

![image](https://user-images.githubusercontent.com/478555/54602288-8ec33c00-4a41-11e9-8fd0-db23cfcedbff.png)

My config:
```
title: 'Dom'
views:
  - id: home
    icon: mdi:home
    title: 'Pomieszczenia'
    background: '#e5e5e5 / center / cover no-repeat url("/local/pictures/bg.jpg") fixed'
    path: home
    panel: true
    cards:
      - type: custom:layout-card
        cards:
          - ...
          - ...
  - id: network
    icon: mdi:ethernet
    title: 'Sieć'
    background: '#e5e5e5 / center / cover no-repeat url("/local/pictures/bg.jpg") fixed'
    path: network
    panel: true
    cards:
      - type: custom:layout-card
        cards:
          - ...
          - ...

```
