### ISSUE TITLE
Stretching the icons in the lovelace-layout-card view dashboard 

### ISSUE THREAD

**Issue by MiAutomations** [thomasloven/lovelace-layout-card#172]
Hello 

I'm trying to stretching the icons present in this card in order to fulfilled all the dashboard in bigger view but I cant understand how to do this

The code 

```yaml
type: horizontal-stack
cards:
  - type: custom:layout-card
    layout_type: custom:horizontal-layout
    title: Reolink
    cards:
      - type: horizontal-stack
        cards:
          - type: custom:button-card
            aspect_ratio: 2/1
            show_live_stream: true
            title: Reolink
            entity: camera.reolink01
            show_name: false
            styles:
              icon:
                - width: 100%
                - margin-left: 0%
          - type: custom:button-card
            aspect_ratio: 2/1
            show_live_stream: true
            title: Reolink
            entity: camera.reolink01
            show_name: false
            styles:
              icon:
                - width: 100%
                - margin-left: 0%
 ```

![image](https://user-images.githubusercontent.com/47602733/144617844-87ad1596-c860-4cf6-aba2-941d2fcf02cd.png)

Can some one please help me in order to fix this ? 

Thank you and best regards
