### ISSUE TITLE
Input select will cause stack-in-card to scroll

### ISSUE THREAD

**Issue by matejdro** [thomasloven/lovelace-layout-card#186]
My Home Assistant version: 2022.3.3 (started happening with the recent "material components update")

Layout-card version: 466df9c

### What I am doing:

I want to display input select inside stack-in-card

### What I expected to happen:

I expect input select to open as an overlay over everything:

![image](https://user-images.githubusercontent.com/507922/158049397-e2fe4ed5-8177-4a62-882d-72f03c5f6451.png)

### What happened instead:

input select will open inside stack-in-card, causing it to scroll 

![Peek 2022-03-13 08-10](https://user-images.githubusercontent.com/507922/158049287-c54f4001-fe76-48c5-9802-b3ce65eb0c77.gif)

### **Minimal** steps to reproduce:

1. Create input_select with several options
2. Display following yaml in lovelace:

```yaml
type: custom:stack-in-card
mode: vertical
keep:
  margin: true
  outer_padding: true
cards:
  - type: markdown
    content: >
      # Test
  - type: entities
    entities:
      - entity: input_select.media_mode
```

Error messages from the browser console:

---

**By putting an X in the boxes ([X]) below, I indicate that I:**

- [X] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).
- [X] Have made sure I am using the latest version of the plugin.
- [X] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.
- [X] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
