### ISSUE TITLE
Grid (layout-card) frozen content when cast dashboard.

### ISSUE THREAD

**Issue by minipav** [thomasloven/lovelace-layout-card#192]
My Home Assistant version: 2022.3.3

Layout-card version (FROM BROWSER CONSOLE): 2.4.2

What I am doing: 
Using a picture-elements card inside a grid (layout-card) to display the sensor.time and sensor.date as a state-label to make a clock on my dashboard

What I expected to happen:
The time to change as time progresses when casting that dashboard on my google nest hub using the HA media player.

What happened instead:
The time is stuck at the time the dashboard started casting to the google nest hub.

**Minimal** steps to reproduce:
1. Create a new blank dashbord
2. Added the Grid (Layout-card)
3. Add the Picture Elements card to the Grid Layout card under cards
4. Paste the below code into the code editor for the Picture Elements card
5. Use and automation with 
- Action: Play media
- Media Player: Google Nest Hub 
- Select created lovelace dashboard

```yaml
# The least ammount of code possible to reproduce my error

type: picture-elements
elements:
  - type: state-label
    entity: sensor.time
    style:
      font-size: 1000%
      top: 50%
      left: 50%
  - type: state-label
    entity: sensor.date
    style:
      color: var(--secondary-text-color)
      font-size: 200%
      top: 90%
      left: 50%
image: /local/ClockTransparentBack.png

# End of code

![ClockTransparentBack](https://user-images.githubusercontent.com/80462963/161946248-e2678c95-5310-44ce-92ba-160b157b9482.png)

```
Error messages from the browser console: None
---

**By putting an X in the boxes ([X]) below, I indicate that I:**

- [X] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).
- [X] Have made sure I am using the latest version of the plugin.
- [X] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.
- [X] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
