### ISSUE TITLE
map card + layout-card: map is displayed erratically

### ISSUE THREAD

**Issue by ildar170975** [thomasloven/lovelace-layout-card#193]
My Home Assistant version: 2022.4.0

Layout-card version (FROM BROWSER CONSOLE): 2.4.2

Win10x64, Chrome.

What I am doing:
1) The `vertical-layout` selected for the view.
2) Two map cards are added on the view.

What I expected to happen:
Map cards are displayed.

What happened instead:
Map cards may not be displayed at all, page refresh (F5) may not help.

**Minimal** steps to reproduce:
1) Create a new view.
2) Add this code for the view:
```
title: test-3
path: test-test-3
type: custom:vertical-layout
badges: []
cards:

  - type: map
    entities:
    - entity: person.ildar

  - type: vertical-stack
    cards:
      - type: entities
        entities:
          - sun.sun
      - type: map
        entities:
        - entity: person.mama
```
3) See if both the map cards are displayed.
In my case just one map was displayed (the 2nd one which is inside `vertical-stack`):
![image](https://user-images.githubusercontent.com/71872483/162094111-c9d293a8-9618-48d2-9fb1-c4aa250fe477.png)

4) Press F5 to refresh the page - usually it does not help but sometimes the 1st map card may be displayed too.

5) Now comment this line:
```
type: custom:vertical-layout
```

6) See if both the map cards are displayed.
In my case both the cards were displayed:
![image](https://user-images.githubusercontent.com/71872483/162094417-7c97bb97-4c72-4338-88fd-e1bfb98ce9cb.png)

7) Now edit the code:
```
title: test-3
path: test-test-3
type: custom:vertical-layout
badges: []
cards:

  - type: map
    entities:
    - entity: person.ildar

  - type: entities
    entities:
      - sun.sun

  - type: map
    entities:
    - entity: person.mama
```

8) See if both the map cards are displayed.
In my case only the Entities card was displayed:
![image](https://user-images.githubusercontent.com/71872483/162094758-1b16ed1b-947f-4622-9f16-f8b7e50174e7.png)

9) Press F5 to refresh the page - usually it does not help but sometimes the 1st & 2nd map cards may be displayed too.

Error messages from the browser console:
None
---

**By putting an X in the boxes ([X]) below, I indicate that I:**

- [x] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).
- [x] Have made sure I am using the latest version of the plugin.
- [x] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.
- [x] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
