### ISSUE TITLE
Parameter "card_margin" ignored when using grid layout

### ISSUE THREAD

**Issue by cdhgee** [thomasloven/lovelace-layout-card#194]
My Home Assistant version: 2022..4.1

Layout-card version (FROM BROWSER CONSOLE): LAYOUT-CARD 2.4.2 IS INSTALLED

What I am doing: Trying to set card margins on nested grid-layouts

What I expected to happen: Margin on cards within the grid is controlled by the `card_margin` parameter

What happened instead: `card_margin` parameter is being ignored and *all* cards have a margin

**Minimal** steps to reproduce:

1. Add a card with the following YAML:

```yaml
type: custom:layout-card
layout_type: custom:grid-layout
layout:
  grid-template-columns: 1fr
  margin: 0
  padding: 0
  card_margin: 0px
cards:
  - type: custom:layout-card
    layout_type: custom:grid-layout
    layout:
      grid-template-columns: repeat(auto-fill, minmax(200px, 1fr))
      margin: 0
      padding: 0
      card_margin: 0px
    cards:
      - type: button
        tap_action:
          action: toggle
        entity: light.garage_work_light
      - type: button
        tap_action:
          action: toggle
        entity: light.garage_work_light
```

2. Observe that there is a gap between the cards. Per the code above the margin should be set to 0 on all sides. 

![image](https://user-images.githubusercontent.com/1256233/162634283-8f32dfa2-9088-4499-a1bc-8ec368ed302d.png)

This appears to be caused by the `#root > *` CSS which is getting injected

![image](https://user-images.githubusercontent.com/1256233/162634307-b5c65003-7c25-4236-92bc-764775898a25.png)

In other layouts which inherit from BaseColumnsLayout, the `--card-margin` CSS variable is set which defaults to the margin shown above, but can be overriden with the `card_margin` parameter. In the grid layout, this is statically set and cannot be overridden with `card_margin`. 

```
        #root > * {
          margin: var(--masonry-view-card-margin, 4px 4px 8px);
        }
```
(grid.ts, lines 147-149)

Would it be possible to update the grid layout so that it uses the `card_margin` parameter if it is defined to correct this behavior?

---

**By putting an X in the boxes ([X]) below, I indicate that I:**

- [X] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).
- [X] Have made sure I am using the latest version of the plugin.
- [X] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.
- [X] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
