### ISSUE TITLE
Theme variables for margin, padding, and card_margin

### ISSUE THREAD

**Issue by Madelena** [thomasloven/lovelace-layout-card#197]
It is repetitive to reset the margin, padding, and card_margin for every single layout-card.

I propose that there should be variables that can be set in the theme so that we don't need to declare those in layout every time.

Instead of having:
```
type: 'custom:layout-card'
layout_type: 'custom:grid-layout'
layout:
  margin: 0
  padding: 0
  card_margin: 1px
```
for every single card, we will have this in the theme instead:

```
--layout-card-grid-margin: 0
--layout-card-grid-padding: 0
--layout-card-grid-card-margin: 1px
--layout-card-masonry-margin: 0
--layout-card-masonry-padding: 0
--layout-card-vertical-stack-margin: 0
--layout-card-vertical-stack-padding: 0
--layout-card-horizontal-stack-margin: 0
--layout-card-horizontal-stack-padding: 0
```

Vertical Stack, Horizontal Stack, and Masonry layouts will use the existing `vertical-stack-card-margin`, `horizontal-stack-card-margin`, and `masonry-view-card-margin` for card_margin respectively.
