### ISSUE TITLE
How to use it with custom:layout-card 

### ISSUE THREAD

**Issue by gbdavidx** [thomasloven/lovelace-layout-card#20]
```
    cards:
      - type: custom:layout-card
        layout: vertical
        cards: 
          - notifications: hide
            type: 'custom:compact-custom-header'
            voice: hide
            cards: 
              - entity: alarm_control_panel.ring_alarm
                name: Ring
                states:
                  - arm_night
                  - arm_home
```
Doesn't seem to work

**Comment by gbdavidx** [comment]
I tried this and doesn't seem to work with the - break
```
views:
  - background: center / cover no-repeat url("/local/day.jpeg")
    badges: null
    cards:
      - type: custom:layout-card
        layout: horizontal
        cards:
          - type: gauge
            name: Tap1
            measurement: visits
            entity: sensor.tap1
          - type: gauge
            name: Tap2
            measurement: visits
            entity: sensor.tap1
          - break  
          - type: horizontal-stack
            cards:
              - type: picture-entity    
                entity: switch.music_downstairs
                image: /local/music_downstairs.png  
              - type: picture-entity
                entity: switch.music
                image: /local/klipsch.png
          - break
          - type: custom:spotify-card
            client_id: 64155e238d6241c8b6749d7f4c0b2fc6
          - break
          - type: entities
            title: example
            entities:
              - entity: binary_sensor.front_door
              - entity: binary_sensor.garage_door
              - entity: binary_sensor.sliding_back_door
```
