### ISSUE TITLE
Apply margin/padding in a mediaquery 

### ISSUE THREAD

**Issue by MadMaxMcKinney** [thomasloven/lovelace-layout-card#205]
It would be great to apply a different margin to the layout based on the screen size. Especially when use with the grid-layout.

```yaml
type: custom:grid-layout
    layout:
      grid-template-columns: 1fr 1fr 1fr
      grid-template-rows: auto
      grid-template-areas: |
        'header header header'
        'col1 col2 col3'
      grid-gap: 16px
      margin: 24px
      mediaquery:
        '(max-width: 900px)':
          grid-template-columns: 100%
          grid-template-areas: |
            "header"
            "col1"
            "col2"
            "col3"
          margin: 8px
```

I haven't tested it yet but also being able to apply a different grid-gap in the mediaquery would be really helpful as well for responsive layouts. Desktop sizes will need larger values compared to their mobile counterparts.
