### ISSUE TITLE
Top badges are not diplayed in masonry layout

### ISSUE THREAD

**Issue by OToussaint** [thomasloven/lovelace-layout-card#208]
My Home Assistant version: 2022.8.7

Layout-card version 2.4.2

What I am doing: Using the custom:masonry-layout as view type

What I expected to happen: See badges at the top of the page

What happened instead: No badges are displayed

```yaml
# The least ammount of code possible to reproduce my error

  - title: Heater
    type: custom:masonry-layout
    badges:
      - entity: sun.sun
    cards: []

# End of code
```

Error messages from the browser console: None

---

**By putting an X in the boxes ([X]) below, I indicate that I:**

- [X] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).
- [X] Have made sure I am using the latest version of the plugin.
- [X] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.
- [X] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
