### ISSUE TITLE
No Elements when casting via cast.show_lovelace_view with custom:grid-layout

### ISSUE THREAD

**Issue by kleinerhobbit** [thomasloven/lovelace-layout-card#209]
My Home Assistant version: 2022.8.7

Layout-card version (FROM BROWSER CONSOLE): 2.4.2

What I am doing: try to cast a dashboard to google-hub

What I expected to happen: show dashboard like in chrome-browser on my pc

What happened instead: only background image gets displayed. no enities and no informations.

**Minimal** steps to reproduce:

```yaml
views:
  - path: grid
    title: Grid layout
    type: custom:grid-layout
    layout:
      grid-template-columns: auto 30px 25%
      grid-template-rows: auto
      grid-template-areas: |
        "header header header"
        "main . sidebar"
        "footer footer footer"
    cards:
      - type: entities
        entities:
          - entity: light.bed_light
        title: '1'
        show_header_toggle: false
        view_layout:
          grid-area: header

```

Error messages from the browser console: unable to get

---

**By putting an X in the boxes ([X]) below, I indicate that I:**

- [x] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).
- [x] Have made sure I am using the latest version of the plugin.
- [x] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.
- [x] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.

**Comment by arsenicks** [comment]
I have the same issue here, tried different layout nothing work outside of masonry default layout..

**Comment by arsenicks** [comment]
@kleinerhobbit you can try this, it seems to help, I've found this in an old version of the README file.

## Note for Home Assistant Cast users

Layout-card doesn't entirely work with Cast at this time. Specifically, the view may or may not load in if you start a Cast directly to a view which uses layout-card.

If you instead load a different view, and then *switch* to the one using layout-card, things seem to be working better. I hope to be able to fix this soon.

**Comment by no2chem** [comment]
@arsenicks I'm seeing the same issue. Is there a way to programmatically switch the layout?

**Comment by arsenicks** [comment]
What I'm doing right now is something like that in my automation and so far so good. It's been running for 2 days and seems to work.

```
action:
  - service: cast.show_lovelace_view
    data:
      entity_id: media_player.cast_salon_haut
      dashboard_path: lovelace
      view_path: default_view
  - delay:
      hours: 0
      minutes: 0
      seconds: 15
      milliseconds: 0
  - service: cast.show_lovelace_view
    data:
      entity_id: media_player.cast_salon_haut
      dashboard_path: lovelace
      view_path: cast_rss_feed
```
