### ISSUE TITLE
Is this error in the console normal/expected?

### ISSUE THREAD

**Issue by SergioRius** [thomasloven/lovelace-layout-card#211]
My Home Assistant version: 2022.8.7

Layout-card version (FROM BROWSER CONSOLE): 2.4.2

What I am doing:

What I expected to happen:

What happened instead:

**Minimal** steps to reproduce:

```yaml
  - type: 'custom:layout-card'
    layout_type: 'custom:grid-layout'

    layout:
      grid-template-columns: >-
        calc( 20% - 24px ) calc( 20% - 24px ) calc( 20% - 24px ) calc( 20% - 24px ) calc(
        20% - 24px )
      grid-column-gap: 32px
      grid-template-areas: |
        "h h h h h"
        "c1 fp fp fp c2"
      mediaquery:
        '(max-width: 512px)':
          grid-template-columns: 1fr
          grid-template-areas: |
            "h"
            "fp"
            "c1"
            "c2"
          margin: 0
        '(max-width: 800px)':
          grid-template-columns: 1fr 1fr
          grid-template-areas: |
            "h h"
            "fp fp"
            "c1 c2"
          margin: 0
        '(max-width: 1128px)':
          grid-template-columns: 1fr 1fr 1fr
          grid-template-areas: |
            "h h h"
            "c1 fp fp"
            "c2 none none"
          margin: 0
        '(max-width: 1440px)':
          grid-template-columns: >-
            calc( 25% - 24px ) calc( 25% - 24px ) calc( 25% - 24px ) calc(
            25% - 24px )
          grid-template-areas: |
            "h h h h"
            "c1 fp fp c2"
          margin: 0
      margin: 0

    view_layout:
      grid-area: cc

    cards:
...
```

Error messages from the browser console:

Showing two times:
![imagen](https://user-images.githubusercontent.com/1693727/192258540-3cd510b9-216c-445c-914e-011825b0bc40.png)

---
**By putting an X in the boxes ([X]) below, I indicate that I:**

- [X] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).
- [X] Have made sure I am using the latest version of the plugin.
- [X] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.
- [X] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
