### ISSUE TITLE
All cards in one column at first load of the dashboard

### ISSUE THREAD

**Issue by Kedryn** [thomasloven/lovelace-layout-card#214]
My Home Assistant version: 2022.09.X

Layout-card version (FROM BROWSER CONSOLE): 2.4.2

What I am doing:
First load of the HA Dashboard

What I expected to happen:
Everything in place where it should be

What happened instead:
All cards are on one column in the middle of the screen
An F5 does not fix the problem

Three dots then Update, instead, fixes the layout
sometimes, even switching Chrome tabs, fixes it.

**Minimal** steps to reproduce:
dunno
      

```yaml
# The least ammount of code possible to reproduce my error
  - type: custom:layout-card
    layout_type: masonry
    layout:
      width: 300
      max_cols: 4
# End of code
```

Error messages from the browser console:

---

**By putting an X in the boxes ([X]) below, I indicate that I:**

- [x] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).
- [x] Have made sure I am using the latest version of the plugin.
- [x] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.
- [x] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
