### ISSUE TITLE
Zooming to Infinity

### ISSUE THREAD

**Issue by MacVille** [thomasloven/lovelace-layout-card#218]
My Home Assistant version: 202210.5

Layout-card version (FROM BROWSER CONSOLE): 2.4.4

What I am doing: I have changed the View to Grid (layout-card)

What I expected to happen: The Cards should be shown over the whole page

What happened instead: The Cards get zoomed to the infinity

**Minimal** steps to reproduce:

```yaml
- theme: Backend-selected
    title: 'Energie detailübersicht '
    path: energie-detailubersicht
    type: custom:grid-layout
    badges: []
    cards:
      - type: custom:swipe-card
        cards:
          - type: custom:mini-graph-card
            icon: mdi:transmission-tower-export
            entities:
              - entity: sensor.stromverbrauch_hochtarif
                name: Hochtarif
                color: '#2cade0'
                name_adaptive_color: true
              - entity: sensor.stromverbrauch_niedertarif
                name: Niedertarif
                color: '#245275'
                name_adaptive_color: true
            name: Energie verbrauch (Monatlich)
            hours_to_show: 730
            aggregate_func: max
            group_by: date
            show:
              graph: bar
              fill: true
              points: true
              legend: true
            tap_action: none
          - type: custom:mini-graph-card
            icon: mdi:transmission-tower-export
            entities:
              - entity: sensor.strom_taglich_hochtarif
                name: Hochtarif
                color: '#2cade0'
                name_adaptive_color: true
              - entity: sensor.strom_taglich_niedertarif
                name: Niedertarif
                color: '#245275'
                name_adaptive_color: true
            name: Energie verbrauch (Täglich)
            hours_to_show: 24
            aggregate_func: max
            group_by: date
            show:
              graph: bar
              fill: true
              points: true
              legend: true
            color_thresholds:
              - value: 4.5
                color: red
```

Error messages from the browser console: No Error from Layout-Cards

---

**By putting an X in the boxes ([X]) below, I indicate that I:**

- [X] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).
- [X] Have made sure I am using the latest version of the plugin.
- [X] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.
- [X] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
