### ISSUE TITLE
justify-content: center

### ISSUE THREAD

**Issue by tieskuh** [thomasloven/lovelace-layout-card#224]
In the code "justify-content: stretch" is hardcoded. I would like to set that to "center". Is is possible to make that a variable?

<img width="637" alt="image" src="https://user-images.githubusercontent.com/115901851/204103020-242700cd-1b1b-49bb-8cef-dff08b26f2e8.png">

If possible I would also like to give that same #root element a max-width.

**Comment by GoNzCiD** [comment]
I'm going just to report this issue....

From my POV, using grid layout, it should be possible to use the [justify-content](https://css-tricks.com/snippets/css/complete-guide-grid/#aa-justify-content) attribute, as described in the documentation, but it isn't exported to the rendered page. 

By adding it manually in the browser dev tools at element level, it works, so it seems that it's not translated despite you declare it in the design.
![imagen](https://user-images.githubusercontent.com/12912439/208421265-3cf9a62b-8fa6-4aa1-92de-536f55a8f4c9.png)


Very pleasant if fixed!

**Comment by Winor** [comment]
Temporary workaround using [card mod](https://github.com/thomasloven/lovelace-card-mod) to change justify-content:
```yaml
type: custom:mod-card
card_mod:
  style:
    layout-card $ grid-layout $: |
      #root {
        justify-content: center; 
      }
card:
  type: custom:layout-card
```
Dirty, but it works …
