### ISSUE TITLE
max_width is ignored

### ISSUE THREAD

**Issue by MrBLJ** [thomasloven/lovelace-layout-card#23]
After trying for so long I give up and ask for help.

Somehow, I can't get max-width working in my config: I get columns with the same width.
I've copied someone's config that's been know to be working (I saw his screens), it is the following:

```
id: roomsalt
panel: true
path: roomsalt
title: Rooms alt
cards:
  - type: custom:layout-card
    layout: vertical
    column_num: 2
    max_width: [40%, 60%]
    cards:
      - type: entity-button  # Header Card - 40% column
        entity: light.hg_bed
        name: test-label-1
        show_icon: false
        show_label: false
        show_name: true
      - type: horizontal-stack
        cards:
          - type: custom:button-card
            template: header
            label: test-label-1
            entity: light.hg_bed
          - type: custom:button-card
            template: header
            label: test-label-1
            entity: light.hg_bed
      - break
      - type: entity-button # Header Card - 60% column
        entity: light.hg_bed
        name: test-label-2
        show_icon: false
        show_label: false
        show_name: true
      - type: horizontal-stack
        cards:
          - type: custom:button-card
            template: header
            label: test-label-2
            entity: light.hg_bed
          - type: custom:button-card
            template: header
            label: test-label-2
            entity: light.hg_bed
          - type: custom:button-card
            template: header
            entity: light.hg_bed
```

And somehow, I get 33% for every column width ...

I'm running home assistant 0.94.3, I tried getting back to 0.93 but the issue remains.

-> Would anyone have a clue about how to fix this ?

**Comment by Gandohr** [comment]
Only thing I can come up with is to try layout: horizontal as the base
  - type: custom:layout-card
    layout: horizontal
    column_num: 2
    max_width: [40%, 60%]

**Comment by etricky** [comment]
I'm also having issues with max_width not being applied. In my case, I configured 2 columns with max_width: [70%, 30%]. What is displayed seems to be the 2 columns with a total width of one as2 columns are displayed but the cards are being cropped to fit the width of that single column. I have also tried to set column_width to 500 but it has no visible change.

![image](https://user-images.githubusercontent.com/6766415/60835523-4760e700-a1bb-11e9-8c0a-19cd6ba94875.png)

Here's my configuration:
```
cards:
  - type: custom:layout-card
    layout: vertical
    column_num: 2    
    max_width: [70%, 30%]
    cards:
      - type: 'custom:bignumber-card'
        entity: sensor.time_date
      - type: 'custom:weather-card'
        entity: weather.dark_sky
        icons: /local/lovelace/weather-card/icons/    
      - type: entities
        show_header_toggle: false
        entities:
        - entity: sensor.house_power_kwh
        - entity: sensor.heating_power_kwh    
      - break
      - type: entities
        entities:
          - entity: person.ricky
          - entity: person.pats
        show_header_toggle: false
        title: Persons
```
I'm running version 0.95.4 but I also had this issue on version 0.94.4

**Comment by zibous** [comment]
Same problem, can't set maxWidth for one column, because :

```
[...]
if(cols.length > 1 && typeof(this.maxWidth) === 'object') {
        div.style.setProperty('max-width', this.maxWidth[i]);
      } else {
        ## -->> Error only number not percent !
        div.style.setProperty('max-width', this.maxWidth+'px');
      }
[...]
```

**Comment by Gandohr** [comment]
<img width="1432" alt="Screenshot 2019-07-09 at 15 25 21" src="https://user-images.githubusercontent.com/218680/60891623-f3f3a500-a25d-11e9-89de-840c20b59337.png">
This is what I get when I use your config, it gives errors cause I don't have bignumber-card and your entities, but layout seems ok

```
id: layout1
title: Layout1
icon: mdi:stairs
panel: true
cards:
  - type: custom:layout-card
    layout: vertical
    column_num: 2    
    max_width: [70%, 30%]
    cards:
      - type: 'custom:bignumber-card'
        entity: sensor.time_date
      - type: 'custom:weather-card'
        entity: weather.dark_sky
        icons: /local/lovelace/weather-card/icons/    
      - type: entities
        show_header_toggle: false
        entities:
        - entity: sensor.house_power_kwh
        - entity: sensor.heating_power_kwh    
      - break
      - type: entities
        entities:
          - entity: person.ricky
          - entity: person.pats
        show_header_toggle: false
        title: Persons
```
