### ISSUE TITLE
Cards disappear on tablet

### ISSUE THREAD

**Issue by RemcoveHA** [thomasloven/lovelace-layout-card#235]
My Home Assistant version: 2023.2.3

Layout-card version (FROM BROWSER CONSOLE): 2.4.4

What I am doing: I am currently trying to make a dashboard for my tablet via de grid option. 

What I expected to happen: I want to make 3 columns for now) with multiple rows. Some cards spend over more then one or two rows.

What happened instead: Cards disappear after a few seconds on my tablet. On my browser the view stays. It seems to only happen in the GRID variant. I currently just added a random 6 light switched in the horizontal variant and they stay visible on the tablet. 

**Minimal** steps to reproduce:

```yaml
views:
  - theme: ios-dark-mode-blue-red-alternative
    title: Home
    type: custom:grid-layout
    layout:
      grid-template-columns: 33% 34% 33%
      grid-template-rows: auto
      grid-template-areas: |
        "box1 box2 box3"
        "box1 box4 box5"
    badges: []
    cards:
      - type: picture
        image: https://demo.home-assistant.io/stub_config/t-shirt-promo.png
        tap_action:
          action: none
        hold_action:
          action: none
        view_layout:
          grid-area: box1
# End of code
```

Error messages from the browser console:

---

**By putting an X in the boxes ([X]) below, I indicate that I:**

- [x] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).
- [x] Have made sure I am using the latest version of the plugin.
- [x] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.
- [x] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
