### ISSUE TITLE
unknow error on reuse

### ISSUE THREAD

**Issue by soulraven** [thomasloven/lovelace-layout-card#237]
My Home Assistant version: 2023.2.5

Layout-card version (FROM BROWSER CONSOLE): LAYOUT-CARD 1.2.1 IS INSTALLED 

```yaml
title: UPS devices
id: ups_devices
path: ups_devices
icon: mdi:battery-charging-high
panel: true
cards:
  - type: custom:layout-card
    layout_type: grid
    layout:
      grid-template-columns: 33% 33% 33%
      grid-template-rows: auto
      grid-template-areas: |
        "ups ups ups"
        "ups ups ups"
    cards:
....
```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'then')
    at p.updateSize (layout-card.js:1:8172)
    at p.firstUpdated (layout-card.js:1:7991)
    at p._$AE (styles.ts:372:1)
    at p.performUpdate (styles.ts:372:1)
    at p.scheduleUpdate (styles.ts:372:1)
    at p._$Ej (styles.ts:372:1)
    at async p._$Ej (styles.ts:372:1)

```javascript
this.requestUpdate().then(()=>this.resizer.observe(this)))

---

**By putting an X in the boxes ([X]) below, I indicate that I:**

- [X] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).
- [X] Have made sure I am using the latest version of the plugin.
- [X] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.
- [X] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
