### ISSUE TITLE
visible state-switch card plus layout-card view with height: auto in view yaml causing 8px x-overflow in mobile view (div=column)

### ISSUE THREAD

**Issue by jack5mikemotown** [thomasloven/lovelace-layout-card#245]
My Home Assistant version: 2022.XX.X

Layout-card version (FROM BROWSER CONSOLE):

What I am doing:
Trying to have a 1 column mobile layout with state-switch cards. I am aware of how particular of an issue this is. height: auto is to fix a similar, already reported but regarding y overflow.

What I expected to happen:
The layout does not let me scroll left or right

What happened instead:
The layout will scroll right, revealing an additional 8 pixels of nothing
**Minimal** steps to reproduce:

```yaml
# The least ammount of code possible to reproduce my error
   - path: test
    icon: ''
    type: custom:vertical-layout
    layout:
      min_height: 4
      height: auto
    badges: []
    cards:
      - type: custom:state-switch
        entity: mediaquery
        states:
          '(max-width: 500px)':
            type: markdown
            content: .
# End of code
```

Error messages from the browser console:
none
---

**By putting an X in the boxes ([X]) below, I indicate that I:**

- [x] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).
- [x] Have made sure I am using the latest version of the plugin.
- [x] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.
- [x] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
