### ISSUE TITLE
anyone has the patience to help me?

### ISSUE THREAD

**Issue by zillion42** [thomasloven/lovelace-layout-card#251]
Hi,

I know it's a lot to ask, but I have this grid layout card with 1456 lines of code, and it stopped working from one day to the next. It relies on many other HACS frontend addons namely:
![image](https://github.com/thomasloven/lovelace-layout-card/assets/36650866/ad3b0660-9e85-46b1-9032-17da307b8aad)

 I have no clue what might be wrong, it's been a while since I wrote it.

Here it goes:
```

type: custom:layout-card
layout_type: grid
layout:
  grid-template-columns: 33% 33% 33%
  grid-template-rows: auto
  grid-template-areas: |
    "Master Master Master"
    "Master2 Master2 Master2"
    "Outside Outside Outside"
    "Area1 Area1 Area1"
    "Mmain1 Mmain2 Mmain3"
    "Mmain11 Mmain22 Mmain33"
    "Mmain111 Mmain222 Mmain333"
    "Area2 Area2 Area2"
    "Area21 Area22 Area23"
    "Area211 Area222 Area233"
    "Area2111 Area2222 Area2333"
    "Area3 Area3 Area3"
    "Area31 Area32 Area33"
    "Area311 Area322 Area333"
    "Area3111 Area3222 Area3333"
    "Flur1 Flur2 Flur3"
cards:
  - type: custom:slider-button-card
    entity: climate.thermostat_hc1
    name: Master Temperature Boiler
    slider:
      direction: left-right
      background: gradient
      use_state_color: false
      use_percentage_bg_opacity: true
      show_track: true
      toggle_on_click: false
      force_square: false
    style: |
      :host {
      --slider-color: red;
      }
    show_name: true
    show_state: true
    compact: true
    view_layout:
      grid-area: Master
  - type: custom:slider-button-card
    entity: climate.heizung_group
    name: Master Temperature Thermostat
    slider:
      direction: left-right
      background: gradient
      use_state_color: false
      use_percentage_bg_opacity: true
      show_track: true
      toggle_on_click: false
      force_square: false
    style: |
      :host {
      --slider-color: red;
      }
    show_name: true
    show_state: true
    compact: true
    view_layout:
      grid-area: Master2
##-------------------------------------------------------
##-------------------------------------------------------
  - type: vertical-stack
    cards:
      - type: custom:mini-graph-card
        entities:
          - entity: sensor.boiler_outside_temperature
            name: Outside Temperature
          - entity: sensor.thermostat_damped_outdoor_temperature
            name: Damped Outside Temperature
          - color: gray
            entity: sun.sun
            name: Sun
            show_line: false
            show_points: false
            show_legend: false
            y_axis: secondary
        points_per_hour: 4
        height: 80
        line_width: 0.3
        hour24: true
        hours_to_show: 96
        show:
          fill: true
          labels: true
          labels_secondary: false
        state_map:
          - value: above_horizon
          - value: below_horizon
        color_thresholds:
          - value: -10.0
            color: '#000000'
          - value: -7.5
            color: '#8a00ff'
          - value: -5.0
            color: '#0000ff'
          - value: -2.0
            color: '#009cff'
          - value: -0.01
            color: '#00deff'
          - value: 0
            color: '#9c00ff'
          - value: 5
            color: '#ff0072'
          - value: 10
            color: '#ff1800'
          - value: 15
            color: '#ff9000'
          - value: 20
            color: '#ffea00'
    view_layout:
      grid-area: Outside
#-------------------------------------------------------------
#------------------------------------------------------------
##-------------------------------------------------------
##-------------------------------------------------------
  - type: vertical-stack
    cards:
      - type: custom:mini-graph-card
        entities:
          - entity: sensor.thermostat_hc1_current_room_temperature
            show_points: false
            name: Wohnzimmer Thermostat
          - entity: sensor.wohn_temperature
            show_points: false
            name: Wohnzimmer
          - entity: sensor.tobi_temperature
            show_points: false
            name: Tobi
          - entity: sensor.kuche_temperature
            show_points: false
            name: Küche
          - color: gray
            entity: sun.sun
            name: Sun
            show_line: false
            show_points: false
            show_legend: false
            y_axis: secondary
        points_per_hour: 4
        height: 80
        line_width: 0.3
        hour24: true
        hours_to_show: 48
        show:
          fill: true
          labels: true
          labels_secondary: false
        state_map:
          - value: above_horizon
          - value: below_horizon
        color_thresholds:
          - value: 16
            color: '#9c00ff'
          - value: 18
            color: '#ff0072'
          - value: 20
            color: '#ff1800'
          - value: 22
            color: '#ff9000'
          - value: 24
            color: '#ffea00'
    view_layout:
      grid-area: Area1
#-------------------------------------------------------------
#-------------------------------------------------------------
  - type: custom:simple-thermostat
    entity: climate.wohnzimmer_heizung_thermostat_2
    header:
      name: Wohnzimmer
    view_layout:
      grid-area: Mmain1
      #-------------------------------------------------------
  - type: custom:layout-card
    layout_type: grid
    layout:
      grid-template-columns: 33% 33% 33%
      grid-template-rows: auto
      grid-template-areas: |
        "button1 button2 button3"
        "button1 button2 button3"
    cards:
      - type: custom:button-card
        entity: switch.wohnzimmer_heizung_switch_9
        show_name: true
        name: Anti Freeze
        show_state: false
        color_type: card
        color: rgb(254, 129, 0)
        icon: mdi:snowflake
        size: 16%
        styles:
          name:
            - font-size: 15px
        action: service
        service:
          domain: input_boolean
          action: toggle
          data:
            entity_id: switch.wohnzimmer_heizung_switch_9
      - type: custom:button-card
        entity: switch.wohnzimmer_heizung_switch_12
        show_name: true
        name: Away Mode
        show_state: false
        color_type: card
        color: rgb(254, 129, 0)
        icon: mdi:logout
        size: 16%
        styles:
          name:
            - font-size: 15px
        action: service
        service:
          domain: input_boolean
          action: toggle
          data:
            entity_id: switch.wohnzimmer_heizung_switch_12
      - type: custom:button-card
        entity: switch.wohnzimmer_heizung_switch_8
        show_name: true
        name: Child Lock
        show_state: false
        color_type: card
        color: rgb(254, 129, 0)
        icon: mdi:human-male-child
        size: 16%
        styles:
          name:
            - font-size: 15px
        action: service
        service:
          domain: input_boolean
          action: toggle
          data:
            entity_id: switch.wohnzimmer_heizung_switch_8
      - type: custom:button-card
        entity: switch.wohnzimmer_heizung_switch_10
        show_name: true
        name: Limescale Protection
        show_state: false
        color_type: card
        color: rgb(254, 129, 0)
        icon: mdi:timer-alert-outline
        size: 16%
        styles:
          name:
            - font-size: 15px
        action: service
        service:
          domain: input_boolean
          action: toggle
          data:
            entity_id: switch.wohnzimmer_heizung_switch_10
      - type: custom:button-card
        entity: switch.wohnzimmer_heizung_switch_11
        show_name: true
        name: Schedule on/off
        show_state: false
        color_type: card
        color: rgb(254, 129, 0)
        icon: mdi:timetable
        size: 16%
        styles:
          name:
            - font-size: 15px
        action: service
        service:
          domain: input_boolean
          action: toggle
          data:
            entity_id: switch.wohnzimmer_heizung_switch_11
      - type: custom:button-card
        entity: switch.wohnzimmer_heizung_switch_7
        show_name: true
        name: Window Detection
        show_state: false
        color_type: card
        color: rgb(254, 129, 0)
        icon: mdi:window-open-variant
        size: 16%
        styles:
          name:
            - font-size: 15px
        action: service
        service:
          domain: input_boolean
          action: toggle
          data:
            entity_id: switch.wohnzimmer_heizung_switch_7
    view_layout:
      grid-area: Mmain11
    #---------------------------------------------------------
  - type: entities
    entities:
      - entity: number.wohnzimmer_heizung_number_temperature_calibration_2
        name: Wohnzimmer Calibration
    view_layout:
      grid-area: Mmain111
#-------------------------------------------------------------
#-------------------------------------------------------------
  - type: custom:simple-thermostat
    entity: climate.tobi_heizung_thermostat
    header:
      name: Tobi
    view_layout:
      grid-area: Mmain2
      #-------------------------------------------------------
  - type: custom:layout-card
    layout_type: grid
    layout:
      grid-template-columns: 33% 33% 33%
      grid-template-rows: auto
      grid-template-areas: |
        "button1 button2 button3"
        "button1 button2 button3"
    cards:
      - type: custom:button-card
        entity: switch.tobi_heizung_switch_3
        show_name: true
        name: Anti Freeze
        show_state: false
        color_type: card
        color: rgb(254, 129, 0)
        icon: mdi:snowflake
        size: 16%
        styles:
          name:
            - font-size: 15px
        action: service
        service:
          domain: input_boolean
          action: toggle
          data:
            entity_id: switch.tobi_heizung_switch_3
      - type: custom:button-card
        entity: switch.tobi_heizung_switch_6
        show_name: true
        name: Away Mode
        show_state: false
        color_type: card
        color: rgb(254, 129, 0)
        icon: mdi:logout
        size: 16%
        styles:
          name:
            - font-size: 15px
        action: service
        service:
          domain: input_boolean
          action: toggle
          data:
            entity_id: switch.tobi_heizung_switch_6
      - type: custom:button-card
        entity: switch.tobi_heizung_switch_2
        show_name: true
        name: Child Lock
        show_state: false
        color_type: card
        color: rgb(254, 129, 0)
        icon: mdi:human-male-child
        size: 16%
        styles:
          name:
            - font-size: 15px
        action: service
        service:
          domain: input_boolean
          action: toggle
          data:
            entity_id: switch.tobi_heizung_switch_2
      - type: custom:button-card
        entity: switch.tobi_heizung_switch_4
        show_name: true
        name: Limescale Protection
        show_state: false
        color_type: card
        color: rgb(254, 129, 0)
        icon: mdi:timer-alert-outline
        size: 16%
        styles:
          name:
            - font-size: 15px
        action: service
        service:
          domain: input_boolean
          action: toggle
          data:
            entity_id: switch.tobi_heizung_switch_4
      - type: custom:button-card
        entity: switch.tobi_heizung_switch_5
        show_name: true
        name: Schedule on/off
        show_state: false
        color_type: card
        color: rgb(254, 129, 0)
        icon: mdi:timetable
        size: 16%
        styles:
          name:
            - font-size: 15px
        action: service
        service:
          domain: input_boolean
          action: toggle
          data:
            entity_id: switch.tobi_heizung_switch_5
      - type: custom:button-card
        entity: switch.tobi_heizung_switch
        show_name: true
        name: Window Detection
        show_state: false
        color_type: card
        color: rgb(254, 129, 0)
        icon: mdi:window-open-variant
        size: 16%
        styles:
          name:
            - font-size: 15px
        action: service
        service:
          domain: input_boolean
          action: toggle
          data:
            entity_id: switch.tobi_heizung_switch
    view_layout:
      grid-area: Mmain22
     #---------------------------------------------------------
  - type: entities
    entities:
      - entity: number.tobi_heizung_number_temperature_calibration
        name: Tobi Calibration
    view_layout:
      grid-area: Mmain222
#-------------------------------------------------------------
#-------------------------------------------------------------
  - type: custom:simple-thermostat
    entity: climate.kuche_heizung_thermostat_3
    header:
      name: Küche
    view_layout:
      grid-area: Mmain3
      #-------------------------------------------------------
  - type: custom:layout-card
    layout_type: grid
    layout:
      grid-template-columns: 33% 33% 33%
      grid-template-rows: auto
      grid-template-areas: |
        "button1 button2 button3"
        "button1 button2 button3"
    cards:
      - type: custom:button-card
        entity: switch.kuche_heizung_switch_15
        show_name: true
        name: Anti Freeze
        show_state: false
        color_type: card
        color: rgb(254, 129, 0)
        icon: mdi:snowflake
        size: 16%
        styles:
          name:
            - font-size: 15px
        action: service
        service:
          domain: input_boolean
          action: toggle
          data:
            entity_id: switch.kuche_heizung_switch_15
      - type: custom:button-card
        entity: switch.kuche_heizung_switch_18
        show_name: true
        name: Away Mode
        show_state: false
        color_type: card
        color: rgb(254, 129, 0)
        icon: mdi:logout
        size: 16%
        styles:
          name:
            - font-size: 15px
        action: service
        service:
          domain: input_boolean
          action: toggle
          data:
            entity_id: switch.kuche_heizung_switch_18
      - type: custom:button-card
        entity: switch.kuche_heizung_switch_14
        show_name: true
        name: Child Lock
        show_state: false
        color_type: card
        color: rgb(254, 129, 0)
        icon: mdi:human-male-child
        size: 16%
        styles:
          name:
            - font-size: 15px
        action: service
        service:
          domain: input_boolean
          action: toggle
          data:
            entity_id: switch.kuche_heizung_switch_14
      - type: custom:button-card
        entity: switch.kuche_heizung_switch_16
        show_name: true
        name: Limescale Protection
        show_state: false
        color_type: card
        color: rgb(254, 129, 0)
        icon: mdi:timer-alert-outline
        size: 16%
        styles:
          name:
            - font-size: 15px
        action: service
        service:
          domain: input_boolean
          action: toggle
          data:
            entity_id: switch.kuche_heizung_switch_16
      - type: custom:button-card
        entity: switch.kuche_heizung_switch_17
        show_name: true
        name: Schedule on/off
        show_state: false
        color_type: card
        color: rgb(254, 129, 0)
        icon: mdi:timetable
        size: 16%
        styles:
          name:
            - font-size: 15px
        action: service
        service:
          domain: input_boolean
          action: toggle
          data:
            entity_id: switch.kuche_heizung_switch_17
      - type: custom:button-card
        entity: switch.kuche_heizung_switch_13
        show_name: true
        name: Window Detection
        show_state: false
        color_type: card
        color: rgb(254, 129, 0)
        icon: mdi:window-open-variant
        size: 16%
        styles:
          name:
            - font-size: 15px
        action: service
        service:
          domain: input_boolean
          action: toggle
          data:
            entity_id: switch.kuche_heizung_switch_13
    view_layout:
      grid-area: Mmain33
     #---------------------------------------------------------
  - type: entities
    entities:
      - entity: number.kuche_heizung_number_temperature_calibration_3
        name: Küche Calibration
    view_layout:
      grid-area: Mmain333
##-------------------------------------------------------
##-------------------------------------------------------
##-------------------------------------------------------
##-------------------------------------------------------
  - type: vertical-stack
    cards:
      - type: custom:mini-graph-card
        entities:
          - entity: sensor.yoshi_temperature
            show_points: false
            name: Yoshi
          - entity: sensor.klo_temperature
            show_points: false
            name: Klo
          - entity: sensor.bad_temperature
            show_points: false
            name: Bad
          - color: gray
            entity: sun.sun
            name: Sun
            show_line: false
            show_points: false
            show_legend: false
            y_axis: secondary
        points_per_hour: 4
        height: 80
        line_width: 0.3
        hour24: true
        hours_to_show: 48
        show:
          fill: true
          labels: true
          labels_secondary: false
        state_map:
          - value: above_horizon
          - value: below_horizon
        color_thresholds:
          - value: 16
            color: '#9c00ff'
          - value: 18
            color: '#ff0072'
          - value: 20
            color: '#ff1800'
          - value: 22
            color: '#ff9000'
          - value: 24
            color: '#ffea00'
    view_layout:
      grid-area: Area2
#-------------------------------------------------------------
#-------------------------------------------------------------
  - type: custom:simple-thermostat
    entity: climate.yoshi_heizung_thermostat
    header:
      name: Yoshi
    view_layout:
      grid-area: Area21
      #-------------------------------------------------------
  - type: custom:layout-card
    layout_type: grid
    layout:
      grid-template-columns: 33% 33% 33%
      grid-template-rows: auto
      grid-template-areas: |
        "button1 button2 button3"
        "button1 button2 button3"
    cards:
      - type: custom:button-card
        entity: switch.yoshi_heizung_switch_3
        show_name: true
        name: Anti Freeze
        show_state: false
        color_type: card
        color: rgb(254, 129, 0)
        icon: mdi:snowflake
        size: 16%
        styles:
          name:
            - font-size: 15px
        action: service
        service:
          domain: input_boolean
          action: toggle
          data:
            entity_id: switch.yoshi_heizung_switch_3
      - type: custom:button-card
        entity: switch.yoshi_heizung_switch_6
        show_name: true
        name: Away Mode
        show_state: false
        color_type: card
        color: rgb(254, 129, 0)
        icon: mdi:logout
        size: 16%
        styles:
          name:
            - font-size: 15px
        action: service
        service:
          domain: input_boolean
          action: toggle
          data:
            entity_id: switch.yoshi_heizung_switch_6
      - type: custom:button-card
        entity: switch.yoshi_heizung_switch_2
        show_name: true
        name: Child Lock
        show_state: false
        color_type: card
        color: rgb(254, 129, 0)
        icon: mdi:human-male-child
        size: 16%
        styles:
          name:
            - font-size: 15px
        action: service
        service:
          domain: input_boolean
          action: toggle
          data:
            entity_id: switch.yoshi_heizung_switch_2
      - type: custom:button-card
        entity: switch.yoshi_heizung_switch_4
        show_name: true
        name: Limescale Protection
        show_state: false
        color_type: card
        color: rgb(254, 129, 0)
        icon: mdi:timer-alert-outline
        size: 16%
        styles:
          name:
            - font-size: 15px
        action: service
        service:
          domain: input_boolean
          action: toggle
          data:
            entity_id: switch.yoshi_heizung_switch_4
      - type: custom:button-card
        entity: switch.yoshi_heizung_switch_5
        show_name: true
        name: Schedule on/off
        show_state: false
        color_type: card
        color: rgb(254, 129, 0)
        icon: mdi:timetable
        size: 16%
        styles:
          name:
            - font-size: 15px
        action: service
        service:
          domain: input_boolean
          action: toggle
          data:
            entity_id: switch.yoshi_heizung_switch_5
      - type: custom:button-card
        entity: switch.yoshi_heizung_switch
        show_name: true
        name: Window Detection
        show_state: false
        color_type: card
        color: rgb(254, 129, 0)
        icon: mdi:window-open-variant
        size: 16%
        styles:
          name:
            - font-size: 15px
        action: service
        service:
          domain: input_boolean
          action: toggle
          data:
            entity_id: switch.yoshi_heizung_switch
    view_layout:
      grid-area: Area211
    #---------------------------------------------------------
  - type: entities
    entities:
      - entity: number.yoshi_heizung_number_temperature_calibration
        name: Yoshi Calibration
    view_layout:
      grid-area: Area2111
#-------------------------------------------------------------
#-------------------------------------------------------------
  - type: custom:simple-thermostat
    entity: climate.klo_heizung_thermostat_2
    header:
      name: Klo
    view_layout:
      grid-area: Area22
      #-------------------------------------------------------
  - type: custom:layout-card
    layout_type: grid
    layout:
      grid-template-columns: 33% 33% 33%
      grid-template-rows: auto
      grid-template-areas: |
        "button1 button2 button3"
        "button1 button2 button3"
    cards:
      - type: custom:button-card
        entity: switch.klo_heizung_switch_9
        show_name: true
        name: Anti Freeze
        show_state: false
        color_type: card
        color: rgb(254, 129, 0)
        icon: mdi:snowflake
        size: 16%
        styles:
          name:
            - font-size: 15px
        action: service
        service:
          domain: input_boolean
          action: toggle
          data:
            entity_id: switch.klo_heizung_switch_9
      - type: custom:button-card
        entity: switch.klo_heizung_switch_12
        show_name: true
        name: Away Mode
        show_state: false
        color_type: card
        color: rgb(254, 129, 0)
        icon: mdi:logout
        size: 16%
        styles:
          name:
            - font-size: 15px
        action: service
        service:
          domain: input_boolean
          action: toggle
          data:
            entity_id: switch.klo_heizung_switch_12
      - type: custom:button-card
        entity: switch.klo_heizung_switch_8
        show_name: true
        name: Child Lock
        show_state: false
        color_type: card
        color: rgb(254, 129, 0)
        icon: mdi:human-male-child
        size: 16%
        styles:
          name:
            - font-size: 15px
        action: service
        service:
          domain: input_boolean
          action: toggle
          data:
            entity_id: switch.klo_heizung_switch_8
      - type: custom:button-card
        entity: switch.klo_heizung_switch_10
        show_name: true
        name: Limescale Protection
        show_state: false
        color_type: card
        color: rgb(254, 129, 0)
        icon: mdi:timer-alert-outline
        size: 16%
        styles:
          name:
            - font-size: 15px
        action: service
        service:
          domain: input_boolean
          action: toggle
          data:
            entity_id: switch.klo_heizung_switch_10
      - type: custom:button-card
        entity: switch.klo_heizung_switch_11
        show_name: true
        name: Schedule on/off
        show_state: false
        color_type: card
        color: rgb(254, 129, 0)
        icon: mdi:timetable
        size: 16%
        styles:
          name:
            - font-size: 15px
        action: service
        service:
          domain: input_boolean
          action: toggle
          data:
            entity_id: switch.klo_heizung_switch_11
      - type: custom:button-card
        entity: switch.klo_heizung_switch_7
        show_name: true
        name: Window Detection
        show_state: false
        color_type: card
        color: rgb(254, 129, 0)
        icon: mdi:window-open-variant
        size: 16%
        styles:
          name:
            - font-size: 15px
        action: service
        service:
          domain: input_boolean
          action: toggle
          data:
            entity_id: switch.klo_heizung_switch_7
    view_layout:
      grid-area: Area222
     #---------------------------------------------------------
  - type: entities
    entities:
      - entity: number.klo_heizung_number_temperature_calibration_2
        name: Klo Calibration
    view_layout:
      grid-area: Area2222
#-------------------------------------------------------------
#-------------------------------------------------------------
  - type: custom:simple-thermostat
    entity: climate.bad_heizung_thermostat_2
    header:
      name: Bad
    view_layout:
      grid-area: Area23
      #-------------------------------------------------------
  - type: custom:layout-card
    layout_type: grid
    layout:
      grid-template-columns: 33% 33% 33%
      grid-template-rows: auto
      grid-template-areas: |
        "button1 button2 button3"
        "button1 button2 button3"
    cards:
      - type: custom:button-card
        entity: switch.bad_heizung_switch_9
        show_name: true
        name: Anti Freeze
        show_state: false
        color_type: card
        color: rgb(254, 129, 0)
        icon: mdi:snowflake
        size: 16%
        styles:
          name:
            - font-size: 15px
        action: service
        service:
          domain: input_boolean
          action: toggle
          data:
            entity_id: switch.bad_heizung_switch_9
      - type: custom:button-card
        entity: switch.bad_heizung_switch_12
        show_name: true
        name: Away Mode
        show_state: false
        color_type: card
        color: rgb(254, 129, 0)
        icon: mdi:logout
        size: 16%
        styles:
          name:
            - font-size: 15px
        action: service
        service:
          domain: input_boolean
          action: toggle
          data:
            entity_id: switch.bad_heizung_switch_12
      - type: custom:button-card
        entity: switch.bad_heizung_switch_8
        show_name: true
        name: Child Lock
        show_state: false
        color_type: card
        color: rgb(254, 129, 0)
        icon: mdi:human-male-child
        size: 16%
        styles:
          name:
            - font-size: 15px
        action: service
        service:
          domain: input_boolean
          action: toggle
          data:
            entity_id: switch.bad_heizung_switch_8
      - type: custom:button-card
        entity: switch.bad_heizung_switch_10
        show_name: true
        name: Limescale Protection
        show_state: false
        color_type: card
        color: rgb(254, 129, 0)
        icon: mdi:timer-alert-outline
        size: 16%
        styles:
          name:
            - font-size: 15px
        action: service
        service:
          domain: input_boolean
          action: toggle
          data:
            entity_id: switch.bad_heizung_switch_10
      - type: custom:button-card
        entity: switch.bad_heizung_switch_11
        show_name: true
        name: Schedule on/off
        show_state: false
        color_type: card
        color: rgb(254, 129, 0)
        icon: mdi:timetable
        size: 16%
        styles:
          name:
            - font-size: 15px
        action: service
        service:
          domain: input_boolean
          action: toggle
          data:
            entity_id: switch.bad_heizung_switch_11
      - type: custom:button-card
        entity: switch.bad_heizung_switch_7
        show_name: true
        name: Window Detection
        show_state: false
        color_type: card
        color: rgb(254, 129, 0)
        icon: mdi:window-open-variant
        size: 16%
        styles:
          name:
            - font-size: 15px
        action: service
        service:
          domain: input_boolean
          action: toggle
          data:
            entity_id: switch.bad_heizung_switch_7
    view_layout:
      grid-area: Area233
     #---------------------------------------------------------
  - type: entities
    entities:
      - entity: number.bad_heizung_number_temperature_calibration_2
        name: Bad Calibration
    view_layout:
      grid-area: Area2333
##-------------------------------------------------------
##-------------------------------------------------------
##-------------------------------------------------------
##-------------------------------------------------------
  - type: vertical-stack
    cards:
      - type: custom:mini-graph-card
        entities:
          - entity: sensor.thermostat_flur_temperatur
            show_points: false
            name: Flur Thermostat
          - entity: sensor.flur_temperature
            show_points: false
            name: Flur
          - entity: sensor.wasch_temperature
            show_points: false
            name: Waschküche
          - color: gray
            entity: sun.sun
            name: Sun
            show_line: false
            show_points: false
            show_legend: false
            y_axis: secondary
        points_per_hour: 4
        height: 80
        line_width: 0.3
        hour24: true
        hours_to_show: 48
        show:
          fill: true
          labels: true
          labels_secondary: false
        state_map:
          - value: above_horizon
          - value: below_horizon
        color_thresholds:
          - value: 16
            color: '#9c00ff'
          - value: 18
            color: '#ff0072'
          - value: 20
            color: '#ff1800'
          - value: 22
            color: '#ff9000'
          - value: 24
            color: '#ffea00'
    view_layout:
      grid-area: Area3
#-------------------------------------------------------------
#-------------------------------------------------------------
  - type: custom:simple-thermostat
    entity: climate.flur_heizung_thermostat
    header:
      name: Flur
    view_layout:
      grid-area: Area31
      #-------------------------------------------------------
  - type: custom:layout-card
    layout_type: grid
    layout:
      grid-template-columns: 33% 33% 33%
      grid-template-rows: auto
      grid-template-areas: |
        "button1 button2 button3"
        "button1 button2 button3"
    cards:
      - type: custom:button-card
        entity: switch.flur_heizung_switch_3
        show_name: true
        name: Anti Freeze
        show_state: false
        color_type: card
        color: rgb(254, 129, 0)
        icon: mdi:snowflake
        size: 16%
        styles:
          name:
            - font-size: 15px
        action: service
        service:
          domain: input_boolean
          action: toggle
          data:
            entity_id: switch.flur_heizung_switch_3
      - type: custom:button-card
        entity: switch.flur_heizung_switch_6
        show_name: true
        name: Away Mode
        show_state: false
        color_type: card
        color: rgb(254, 129, 0)
        icon: mdi:logout
        size: 16%
        styles:
          name:
            - font-size: 15px
        action: service
        service:
          domain: input_boolean
          action: toggle
          data:
            entity_id: switch.flur_heizung_switch_6
      - type: custom:button-card
        entity: switch.flur_heizung_switch_2
        show_name: true
        name: Child Lock
        show_state: false
        color_type: card
        color: rgb(254, 129, 0)
        icon: mdi:human-male-child
        size: 16%
        styles:
          name:
            - font-size: 15px
        action: service
        service:
          domain: input_boolean
          action: toggle
          data:
            entity_id: switch.flur_heizung_switch_2
      - type: custom:button-card
        entity: switch.flur_heizung_switch_4
        show_name: true
        name: Limescale Protection
        show_state: false
        color_type: card
        color: rgb(254, 129, 0)
        icon: mdi:timer-alert-outline
        size: 16%
        styles:
          name:
            - font-size: 15px
        action: service
        service:
          domain: input_boolean
          action: toggle
          data:
            entity_id: switch.flur_heizung_switch_4
      - type: custom:button-card
        entity: switch.flur_heizung_switch_5
        show_name: true
        name: Schedule on/off
        show_state: false
        color_type: card
        color: rgb(254, 129, 0)
        icon: mdi:timetable
        size: 16%
        styles:
          name:
            - font-size: 15px
        action: service
        service:
          domain: input_boolean
          action: toggle
          data:
            entity_id: switch.flur_heizung_switch_5
      - type: custom:button-card
        entity: switch.flur_heizung_switch
        show_name: true
        name: Window Detection
        show_state: false
        color_type: card
        color: rgb(254, 129, 0)
        icon: mdi:window-open-variant
        size: 16%
        styles:
          name:
            - font-size: 15px
        action: service
        service:
          domain: input_boolean
          action: toggle
          data:
            entity_id: switch.flur_heizung_switch
    view_layout:
      grid-area: Area311
    #---------------------------------------------------------
  - type: entities
    entities:
      - entity: number.flur_heizung_number_temperature_calibration
        name: Flur Calibration
    view_layout:
      grid-area: Area3111
#-------------------------------------------------------------
#-------------------------------------------------------------
  - type: custom:simple-thermostat
    entity: climate.waschkuche_heizung_thermostat_2
    header:
      name: Waschküche
    view_layout:
      grid-area: Area32
      #-------------------------------------------------------
  - type: custom:layout-card
    layout_type: grid
    layout:
      grid-template-columns: 33% 33% 33%
      grid-template-rows: auto
      grid-template-areas: |
        "button1 button2 button3"
        "button1 button2 button3"
    cards:
      - type: custom:button-card
        entity: switch.waschkuche_heizung_switch_9
        show_name: true
        name: Anti Freeze
        show_state: false
        color_type: card
        color: rgb(254, 129, 0)
        icon: mdi:snowflake
        size: 16%
        styles:
          name:
            - font-size: 15px
        action: service
        service:
          domain: input_boolean
          action: toggle
          data:
            entity_id: switch.waschkuche_heizung_switch_9
      - type: custom:button-card
        entity: switch.waschkuche_heizung_switch_12
        show_name: true
        name: Away Mode
        show_state: false
        color_type: card
        color: rgb(254, 129, 0)
        icon: mdi:logout
        size: 16%
        styles:
          name:
            - font-size: 15px
        action: service
        service:
          domain: input_boolean
          action: toggle
          data:
            entity_id: switch.waschkuche_heizung_switch_12
      - type: custom:button-card
        entity: switch.waschkuche_heizung_switch_8
        show_name: true
        name: Child Lock
        show_state: false
        color_type: card
        color: rgb(254, 129, 0)
        icon: mdi:human-male-child
        size: 16%
        styles:
          name:
            - font-size: 15px
        action: service
        service:
          domain: input_boolean
          action: toggle
          data:
            entity_id: switch.waschkuche_heizung_switch_8
      - type: custom:button-card
        entity: switch.waschkuche_heizung_switch_10
        show_name: true
        name: Limescale Protection
        show_state: false
        color_type: card
        color: rgb(254, 129, 0)
        icon: mdi:timer-alert-outline
        size: 16%
        styles:
          name:
            - font-size: 15px
        action: service
        service:
          domain: input_boolean
          action: toggle
          data:
            entity_id: switch.waschkuche_heizung_switch_10
      - type: custom:button-card
        entity: switch.waschkuche_heizung_switch_11
        show_name: true
        name: Schedule on/off
        show_state: false
        color_type: card
        color: rgb(254, 129, 0)
        icon: mdi:timetable
        size: 16%
        styles:
          name:
            - font-size: 15px
        action: service
        service:
          domain: input_boolean
          action: toggle
          data:
            entity_id: switch.waschkuche_heizung_switch_11
      - type: custom:button-card
        entity: switch.waschkuche_heizung_switch_7
        show_name: true
        name: Window Detection
        show_state: false
        color_type: card
        color: rgb(254, 129, 0)
        icon: mdi:window-open-variant
        size: 16%
        styles:
          name:
            - font-size: 15px
        action: service
        service:
          domain: input_boolean
          action: toggle
          data:
            entity_id: switch.waschkuche_heizung_switch_7
    view_layout:
      grid-area: Area322
     #---------------------------------------------------------
  - type: entities
    entities:
      - entity: number.waschkuche_heizung_number_temperature_calibration_2
        name: Waschküche Calibration
    view_layout:
      grid-area: Area3222
##-------------------------------------------------------
##-------------------------------------------------------
  - type: vertical-stack
    cards:
      - type: custom:mini-graph-card
        entities:
          - entity: sensor.thermostat_flur_temperatur
            show_points: false
            name: Flur Thermostat Temperature
          - color: gray
            entity: sun.sun
            name: Sun
            show_line: false
            show_points: false
            show_legend: false
            y_axis: secondary
        points_per_hour: 4
        height: 160
        line_width: 0.3
        hour24: true
        hours_to_show: 48
        show:
          fill: true
          labels: true
          labels_secondary: false
        state_map:
          - value: above_horizon
          - value: below_horizon
        color_thresholds:
          - value: 16
            color: '#9c00ff'
          - value: 18
            color: '#ff0072'
          - value: 20
            color: '#ff1800'
          - value: 22
            color: '#ff9000'
          - value: 24
            color: '#ffea00'
    view_layout:
      grid-area: Flur1
##-------------------------------------------------------
##-------------------------------------------------------
  - type: vertical-stack
    cards:
      - type: custom:mini-graph-card
        entities:
          - entity: sensor.thermostat_flur_humidity
            show_points: false
            name: Flur Thermostat Humidity
          - color: gray
            entity: sun.sun
            name: Sun
            show_line: false
            show_points: false
            show_legend: false
            y_axis: secondary
        points_per_hour: 4
        height: 160
        line_width: 0.3
        hour24: true
        hours_to_show: 48
        show:
          fill: true
          labels: true
          labels_secondary: false
        state_map:
          - value: above_horizon
          - value: below_horizon
        color_thresholds:
          - value: 40
            color: '#00ff6c'
          - value: 60
            color: '#00baff'
    view_layout:
      grid-area: Flur2
##-------------------------------------------------------
##-------------------------------------------------------
  - type: vertical-stack
    cards:
      - type: custom:mini-graph-card
        entities:
          - entity: sensor.thermostat_flur_pressure
            show_points: false
            name: Flur Thermostat Pressure
          - color: gray
            entity: sun.sun
            name: Sun
            show_line: false
            show_points: false
            show_legend: false
            y_axis: secondary
        points_per_hour: 4
        height: 160
        line_width: 0.3
        hour24: true
        hours_to_show: 48
        show:
          fill: true
          labels: true
          labels_secondary: false
        state_map:
          - value: above_horizon
          - value: below_horizon
        color_thresholds:
          - value: 800
            color: '#9c00ff'
          - value: 1200
            color: '#ff0072'
    view_layout:
      grid-area: Flur3

```
