### ISSUE TITLE
Card sometimes isn't showing

### ISSUE THREAD

**Issue by CodexHere** [thomasloven/lovelace-layout-card#252]
My Home Assistant version: 2023.7

Layout-card version 2.4.4

What I am doing:

Using `auto-entities` to display `tile` cards for my fans. 

What I expected to happen:

`tile` cards should show the entities expected 100% of the time.

What happened instead:

70+% of the time the cards are not shown on (PC) browser page refresh or android app load. It requires many refreshes to finally appear. Using `auto-entities` with `glance` or `entities` card renders perfectly fine, every time. Using `layout-card` with either of these result in the same issue of it not appearing most of the time, with or without `auto-entities` involved.

**Minimal** steps to reproduce:

Here I'm using a `veritcal-stack` to provide a header title, but it fails consistently without it as well:

```yaml
type: vertical-stack
title: Fans
cards:
  - type: 'custom:auto-entities'
    card:
      type: custom:layout-card
    filter:
      include:
        - domain: fan
          options:
            type: tile
            features:
              - type: "fan-speed"
    sort:
      method: state
      reverse: true
```

Error messages from the browser console: N/A

---

**By putting an X in the boxes ([X]) below, I indicate that I:**

- [x] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).
- [x] Have made sure I am using the latest version of the plugin.
- [x] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.
- [x] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
