### ISSUE TITLE
horizontal-layout: unneeded scrollbar

### ISSUE THREAD

**Issue by ildar170975** [thomasloven/lovelace-layout-card#261]
My Home Assistant version: 2023.11.2

Layout-card version (FROM BROWSER CONSOLE): 2.4.4

What I am doing:
Consider this code:
```
title: test-6
path: test-6
cards:
  - &ref_card
    type: entities
    entities:
      - sun.sun
      - sun.sun
      - sun.sun
      - sun.sun
      - sun.sun
      - sun.sun
      - sun.sun
      - sun.sun
      - sun.sun
      - sun.sun
      - sun.sun
      - sun.sun
      - sun.sun
      - sun.sun
      - sun.sun
  - *ref_card
  - *ref_card
  - *ref_card
```
which gives us this:

![image](https://github.com/thomasloven/lovelace-layout-card/assets/71872483/e1c5bea5-1651-499e-9b01-6ef4cc64966b)

Now let's add a horizontal layout:
```
title: test-6
path: test-6
type: custom:horizontal-layout
cards:
  ...
```
I see an unneeded scrollbar on the right:

![image](https://github.com/thomasloven/lovelace-layout-card/assets/71872483/8ae43b9c-ade4-4990-8edf-6204722a40af)

What I expected to happen:
A scrollbar here is not needed - so it is not supposed to be shown.

What happened instead:
A scrollbar is displayed.

Error messages from the browser console:
none

---

**By putting an X in the boxes ([X]) below, I indicate that I:**

- [x] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).
- [x] Have made sure I am using the latest version of the plugin.
- [x] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.
- [x] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
