### ISSUE TITLE
iframe doesnt work in panel layout

### ISSUE THREAD

**Issue by seancmalloy** [thomasloven/lovelace-layout-card#264]
My Home Assistant version: 2022.XX.X

Layout-card version (FROM BROWSER CONSOLE): 2.4.4

What I am doing: trying to create single panel to fill entire dashboard (embedded look, no card boarders) with iframe card

What I expected to happen: webpage to display

What happened instead: nothing, doesnt show page

**Minimal** steps to reproduce:

```yaml
# The least ammount of code possible to reproduce my error

type: custom:layout-card
layout_type: panel
layout: {}
cards:
  - type: iframe
    url: https://www.home-assistant.io
    aspect_ratio: 50%

# End of code

![Screenshot (58)](https://github.com/thomasloven/lovelace-layout-card/assets/23019226/5147845a-73e1-499c-81ec-16b8777c6010)


```

Error messages from the browser console:

---

**By putting an X in the boxes ([X]) below, I indicate that I:**

- [] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).
- [] Have made sure I am using the latest version of the plugin.
- [] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.
- [] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
