### ISSUE TITLE
Layout for large and small devices...

### ISSUE THREAD

**Issue by zibous** [thomasloven/lovelace-layout-card#27]
What am I doing wrong or not doing it with "custom: layout-card"? I'm trying to create a layout for large and small screens, but it does not work.

![CARD_LAYOUTS](https://user-images.githubusercontent.com/30198737/61137395-b5602380-a4c5-11e9-9129-537e7ffa5aff.jpg)

```yaml
badges: []
title: My Testview
panel: true
cards:
- type: custom:layout-card
  layout: vertical
  cards:
    ## the big card on top
    - type: picture
      image: https://images.unsplash.com/photo-1512917774080-9991f1c4c750?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=800&h=600&q=80
    - break
    ## small cards 2 per row for large screens
    - type: picture
      image: https://images.unsplash.com/photo-1521446477144-773b2dd9b1af?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=800&h=600&q=80
    - type: picture
      image: https://images.unsplash.com/photo-1546551613-09c2f83e1ede?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=800&h=600&q=80
    - break
    - type: picture
      image: https://images.unsplash.com/photo-1560635921-171138a3955e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=800&h=600&q=80
    - type: picture
      image: https://images.unsplash.com/photo-1545022274-cdffe6d68075?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=800&h=600&q=80
    ## the big card on bottom
    - type: picture
      image: https://images.unsplash.com/photo-1544984243-ec57ea16fe25?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=800&h=600&q=80
    - break

```
