### ISSUE TITLE
Only one centered Column instead of three in vertical-layout - HA 2024.6. beta

### ISSUE THREAD

**Issue by VDRainer** [thomasloven/lovelace-layout-card#288]
My Home Assistant version: 2024.6.0b3

Layout-card version (FROM BROWSER CONSOLE): 2.4.5

What I am doing:
Since HA 2024.6.0b3 there is only one centered column.

What I expected to happen:
3 Columns

What happened instead:
Only one centered column

**Minimal** steps to reproduce:
![20240531_194352](https://github.com/thomasloven/lovelace-layout-card/assets/26381449/2ee32f2e-783d-4953-b74c-92a141915448)

```yaml
title: Baustelle
path: baustelle
icon: mdi:account-hard-hat
visible:
  - user: xxxx
type: custom:vertical-layout
layout:
  max_cols: 3

cards:

# Column 1
  - type: vertical-stack
    cards:

      - type: custom:auto-entities
        card:
          type: entities
          title: Column 1
          show_header_toggle: false
        filter:
          include:
            - entity_id: "*.vw_*"
          exclude:
            - entity_id: "*.vw_api_*"
        sort:
          method: domain
          reverse: true

  - type: custom:layout-break

# Column 2 
  - type: vertical-stack
    cards:

      - type: entities
        title: Column 2
        show_header_toggle: false
        state_color: true
        entities:
          - entity: sensor.ug_kn_temperature
            name: Temperatur
            icon: mdi:thermometer-lines
          - entity: sensor.ug_kn_humidity
            name: Luftfeuchte
            icon: mdi:water-percent
```

Error messages from the browser console: Nothing

---

**By putting an X in the boxes ([X]) below, I indicate that I:**

- [x] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).
- [x] Have made sure I am using the latest version of the plugin.
- [x] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.
- [x] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
