### ISSUE TITLE
layout-card resets style

### ISSUE THREAD

**Issue by DTekNOdev** [thomasloven/lovelace-layout-card#289]
When I use the grid layout as the view directly in a dashboard all is fine and cards are rendered with rounded corners. However (#287) in order to render correctly on a nest hub, it is necessary to use a panel view with a layout-card inside (I know, it says not recommended, but I have no choice). Using the layout-card with a grid-layout is necessary to render the dashboard on a nest hub, but the ha-card-border-radius is lost, ie it is reset to zero somewhere and the cards are rendered with square corners.

The only workaround I have found is to use card_mod on every card to set the border-radius and I don't want to do that.

It makes no difference whether or not  I use a theme that sets the border-radius.

My Home Assistant version: 2024.5.4

Layout-card version (FROM BROWSER CONSOLE): 2.4.5

What I am doing:

Using layout-card to render a panel 

What I expected to happen:

The panel should be rendered with rounded corners in the individual cards

What happened instead:

The ha-card-border-radius is set to zero

**Minimal** steps to reproduce:

Create a new dashboard and replace the raw yaml with this:

```yaml
# The least amount of code possible to reproduce my error
views:
  - title: test again
    path: test-again
    type: panel
    cards:
      - type: custom:layout-card
        layout_type: custom:grid-layout
        layout:
          grid-template-columns: repeat(3,auto)
          grid-template-rows: auto
          grid-template-areas: |
            "r1c1 r1c2 r1c3"
            "r2c1 r2c2 r2c3"
        cards:
          - type: markdown
            view_layout:
              grid-area: r1c1
            content: '## Placeholder'
          - type: markdown
            view_layout:
              grid-area: r1c2
            content: '## Placeholder'
          - type: markdown
            view_layout:
              grid-area: r1c3
            content: '## Placeholder'

# End of code
```
![image](https://github.com/thomasloven/lovelace-layout-card/assets/8317651/120b6f53-231f-4837-b095-c3605b33214e)

Using a grid-layout view:

![image](https://github.com/thomasloven/lovelace-layout-card/assets/8317651/f80914f0-5dbe-49f6-ab17-fdd591caab82)

Error messages from the browser console:

None

---

**By putting an X in the boxes ([X]) below, I indicate that I:**

- [x] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).
- [x] Have made sure I am using the latest version of the plugin.
- [x] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.
- [x] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
