### ISSUE TITLE
FR: add width to breakpoints

### ISSUE THREAD

**Issue by iantrich** [thomasloven/lovelace-layout-card#29]
Add optional configuration values to the `break` e.g.

```yaml
- break:
  width: 800
  operator: '>'
```
Without those supplied, would perform as it does currently.
