### ISSUE TITLE
[SUPPORT] Help with layout?

### ISSUE THREAD

**Issue by deanfourie1** [thomasloven/lovelace-layout-card#297]
So this is more of a request for help with a layout, I have been struggling to get a specific layout working and have posted in quite a few places and no one can help me.

I am trying to make a layout like this. Is not to scale but its basically a weather dashboard that I want to have a large card in the middle, which will be a weather radar and then all other rain, wind cards etc positioned around that card.

![Untitled](https://github.com/thomasloven/lovelace-layout-card/assets/71812804/6392b839-620e-41bd-a10f-54db49701acc)

Is anyone able to help me with this layout please?

Thank you very much!

**Comment by red4dj** [comment]
I did not test this, but I believe it would be the following:
```yaml
type: custom:layout-card
layout_type: custom:grid-layout
cards:
  - type: ...
    view_layout:
      grid-area: a
  - type: ...
    view_layout:
      grid-area: b
  - type: ...
    view_layout:
      grid-area: main
  ...
layout:
  grid-template-areas: |
    "a b c d"
    "e main main f"
    "g h i j"
```
