### ISSUE TITLE
Thermostat entities in horizontal layout-card have wrong height after upgraded to 2024.7

### ISSUE THREAD

**Issue by xmcp** [thomasloven/lovelace-layout-card#299]
My Home Assistant version: 2024.7.2

Layout-card version (FROM BROWSER CONSOLE): 2.4.5

What I am doing: I have multiple thermostat cards in a horizontal layout-card. I upgraded home assistant from 2024.6.x to 2024.7.2.

What I expected to happen: The page should look like this (in 2024.6.x).

![image](https://github.com/user-attachments/assets/7b6c0550-f97f-40a3-9838-26cd8bf4942e)

What happened instead: After the upgrade, the thermostat cards have incorrect height.

![image](https://github.com/user-attachments/assets/769d4072-9d1b-4a0b-8903-5c4aa95c2a1d)

**Minimal** steps to reproduce:

1. Set up a climate entity. Assume that it has the entity ID `climate.thermo`.
2. Add the below UI into lovelace.
3. Confirm that the height is incorrect.

```yaml
views:
  - title: Home
    cards:
      - type: custom:layout-card
        layout_type: custom:horizontal-layout
        layout: {}
        cards:
          - type: thermostat
            entity: climate.thermo
          - type: thermostat
            entity: climate.thermo
          - type: thermostat
            entity: climate.thermo
          - type: thermostat
            entity: climate.thermo
          - type: thermostat
            entity: climate.thermo
    type: custom:vertical-layout
    layout:
      max_width: 1600
```

This issue can be fixed by adding the below CSS to each of the thermostat cards:

```yaml
card_mod:
  style: |
    :host {
      height: unset !important;
    }
```

Error messages from the browser console:

No.

---

**By putting an X in the boxes ([X]) below, I indicate that I:**

- [X] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).
- [X] Have made sure I am using the latest version of the plugin.
- [X] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.
- [X] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
