### ISSUE TITLE
Blocks the Lovelace editor

### ISSUE THREAD

**Issue by bieniu** [thomasloven/lovelace-layout-card#3]
layout-card blocks UI Lovelace editor in HA 0.83.x. There are no EDIT button under the cards.

With layout-card:
![image](https://user-images.githubusercontent.com/478555/49327205-9b895600-f55e-11e8-9570-4eaf31b87fba.png)

Without layout-card:
![image](https://user-images.githubusercontent.com/478555/49327234-2cf8c800-f55f-11e8-9380-2c2ebe57ec7b.png)

Configuration:
```
- id: energy
    icon: mdi:power-plug
    title: 'Energia'
    panel: true
    cards:
      - id: layout_card
        type: custom:layout-card
        cards:
          - id: .....
          - id: .....
```
