### ISSUE TITLE
Grid layout is not working anymore after (I think) Upgrade to 2025.1.1

### ISSUE THREAD

**Issue by cedricdelecole** [thomasloven/lovelace-layout-card#308]
My Home Assistant version: 2025.1.1

Layout-card version (FROM BROWSER CONSOLE):

What I am doing: after upgrade to 2025.1.1, my custom-grid:layout is not recognized anymore ... see screenshot below :  

![image](https://github.com/user-attachments/assets/aef30a0d-549a-4e7e-8201-446407439a55)

What I expected to happen:
Dashboard displays as previously

What happened instead:

**Minimal** steps to reproduce:

```yaml
# The least ammount of code possible to reproduce my error
kiosk_mode:
  admin_settings:
    hide_header: false
    hide_sidebar: false
  non_admin_settings:
    kiosk: true
views:
  - title: Home
    type: custom:grid-layout
    layout:
      grid-template-rows: 75px 650px 75px
      grid-template-columns: 420px 500px 420px
      grid-template-areas: |
        "head1 head2 head3"
        "col1 col2 col3"
        "foot1 foot1 foot1"
    icon: mdi:home
    visible:
      - user: 6c0f22e61daf4f799222ab1f2942f2af
      - user: 1a22f3b4ca2f4c4c84db909d9ba20c60
    badges: []
    cards:
      - type: horizontal-stack
        cards:
          - type: custom:mushroom-person-card
# End of code
```

Error messages from the browser console:

---

**By putting an X in the boxes ([X]) below, I indicate that I:**

- [x] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).
- [x] Have made sure I am using the latest version of the plugin.
- [x] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.
- [x] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
