### ISSUE TITLE
"grid-template-columns: 50% auto" may not work properly for history-graph

### ISSUE THREAD

**Issue by ildar170975** [thomasloven/lovelace-layout-card#310]
My Home Assistant version: 2025.1

Layout-card version (FROM BROWSER CONSOLE): 2.4.5

What I am doing:
Trying to apply `grid-template-columns: 50% auto` layout.

Works OK in Editor:
![image](https://github.com/user-attachments/assets/80ce4f18-6c2e-4f8b-8b55-45addecd47d4)

But causes overflow in a view:
![image](https://github.com/user-attachments/assets/4a2e63e2-c38c-435b-840d-de7c86e415f9)

Have to use `grid-template-columns: 50% 50%` layout:
![image](https://github.com/user-attachments/assets/10a99fc7-23c2-45a4-b024-00dcfa35a337)

Interestingly this glitch does not occur with Entities card:
![image](https://github.com/user-attachments/assets/008a1c2c-cc37-43d0-b474-eb07cd2f7098)

**Minimal** steps to reproduce:

```yaml
type: custom:layout-card
layout_type: custom:grid-layout
layout:
  grid-template-columns: 50% auto
cards:
  - type: history-graph
    entities:
      - sun.sun
  - type: history-graph
    entities:
      - sun.sun
```

Error messages from the browser console:

---

**By putting an X in the boxes ([X]) below, I indicate that I:**

- [] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).
- [] Have made sure I am using the latest version of the plugin.
- [] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.
- [] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
