### ISSUE TITLE
justifying and aligning don't take effekt

### ISSUE THREAD

**Issue by perlchamp** [thomasloven/lovelace-layout-card#312]
My Home Assistant version:
Core 2025.2.4
Supervisor 2025.02.1
Operating System 14.2
Frontend 20250214.0

Layout-card version (FROM BROWSER CONSOLE):
v2.4.5

What I am doing:
i did use 
justify-content: start
justify-self: start
justify-items: start

What I expected to happen:
the button should be justified to the left

What happened instead:
nothing changed. It is still centered

**Minimal** steps to reproduce:
create a new empty dashboard -> paste the code below to the raw configuratione editor -> save
I can't attach the svg-file for the button-card. But this should not cause a problem... imo

```yaml
views:
  - title: WG 4
    type: custom:layout-card
    layout_type: custom:grid-layout
    config:
      show_side_bar: false
      show_app_header: false
    layout:
      grid-template-columns: auto 390px
      grid-template-rows: 35px max-content 25px
      gap: 0
      justify-content: start
      justify-items: start
    cards:
      - type: custom:layout-card
        layout_type: custom:horizontal-layout
        layout:
          margin: '-4px 0px 0px -4px'
          padding: 0
          max_cols: 30
          width: 27
        view_layout:
          grid-area: 1 / 1 / 2 / 2
          gap: 0
          justify-self: start
        cards:
          - type: custom:button-card
            show_entity_picture: true
            entity_picture: /local/img/button/dg-logo.svg
            view_layout:
              justify-self: start
            tap_action:
              action: navigate
              navigation_path: /dashboard-grundriss/0
            styles:
              card:
                - border-radius: 0px;
                - background-color: rgb(50,50,50);
                - max-height: 30px;
                - width: 27px;
                - min-width: 27px;
                - max-width: 27px;
                - padding: 0px;
                - margin: 0px;
                - border: 1px solid orange;
              entity_picture:
                - width: 25px;
```

Error messages from the browser console:
I'm a beginner and don't know, if these messages are caused by layout-card:
Error: Promised response from onMessage listener went out of scope

A lot of warnings like these; two warnings directly under the entry "LAYOUT-CARD 2.4.5 IS INSTALLED" are :
Source-Map-Fehler: NetworkError when attempting to fetch resource.
Ressourcen-Adresse: http://homeassistant.local:8123/frontend_latest/81394.ed17aad1f41d2889.js
Source-Map-Adresse: 81394.ed17aad1f41d2889.js.map

Source-Map-Fehler: NetworkError when attempting to fetch resource.
Ressourcen-Adresse: http://homeassistant.local:8123/frontend_latest/74763.f6d9423fe4eab49b.js
Source-Map-Adresse: 74763.f6d9423fe4eab49b.js.map
---

**By putting an X in the boxes ([X]) below, I indicate that I:**

- [X] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).
- [X] Have made sure I am using the latest version of the plugin.
- [X] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.
- [X] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
