### ISSUE TITLE
custom element doesn't exist: grid-layout

### ISSUE THREAD

**Issue by Brkie** [thomasloven/lovelace-layout-card#314]
My Home Assistant version: 
2025.3.4

Layout-card version (FROM BROWSER CONSOLE): 
2.4.5

What I am doing:
Restart of HA

What I expected to happen:
Normally load my grid

What happened instead:
custom element doesn't exist: grid-layout after 2-3 minuts from full restart

**Minimal** steps to reproduce:

```yaml
views:
  - type: custom:grid-layout
    path: 0
    layout:
      #default
      margin: 0
      grid-gap: var(--custom-layout-card-padding)
      grid-template-columns: repeat(5, 1fr) 0
      grid-templöate-rows: 0 repeat(3, fit-content(100%)) 0fr 
      grid-template-areas: |
        "sidebar  .           .            .           .       ."
        "sidebar  hall        kök          vardagsrum  sovrum  ."
        "sidebar  media       övervåning   övrigt      hemma   ."
        "sidebar  footer      footer       footer      footer  ."
      mediaquery:
        #phone
        "(max-width: 800px)":
          grid-gap: calc(var(--custom-layout-card-padding) * 1.7)
          grid-template-columns: 0 repeat(2, 1fr) 0
          grid-template-rows: 0 repeat(4, fit-content(100%)) 0fr
          grid-template-areas: |
            ".  .           .             ."
            ".  sidebar     sidebar       ."
            ".  hall        kök           ."
            ".  vardagsrum  sovrum        ."
            ".  övervåning  övrigt        ." 
            ".  media       hemma         ."
            ".  footer      footer        ."
            ".  .           .             ."
        #portrait
        "(max-width: 1200px)":
          grid-gap: var(--custom-layout-card-padding)
          grid-template-columns: repeat(3, 1fr) 0
          grid-template-rows: 0 repeat(3, fit-content(100%)) 0fr
          grid-template-areas: |
            "sidebar  .           .       ."
            "sidebar  hall        kök.    ."
            "sidebar  vardagsrum  sovrum  ."
            "sidebar  övervåning  media   ."
            "sidebar  övrigt      hemma   ."
            "sidebar  footer      footer  ."
            "sidebar  .           .       ."
    cards:
      - type: custom:button-card #extra_styles fix
        styles: { card: [display: none] }
```

Error messages from the browser console:
0:1 Uncaught (in promise) ObjectUnderstand this errorAI
ha-yaml-editor.ts:144 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'localize')
    at o.value (ha-yaml-editor.ts:144:33)
    at card-mod.js:1:38742
    at d (card-mod.js:1:2813)
    at Generator.<anonymous> (card-mod.js:1:4159)
    at Generator.next (card-mod.js:1:3242)
    at y (card-mod.js:1:8728)
    at a (card-mod.js:1:8931)
---

**By putting an X in the boxes ([X]) below, I indicate that I:**

- [X] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).
- [X] Have made sure I am using the latest version of the plugin.
- [X] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.
- [X] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
