### ISSUE TITLE
custom element doesn't exist: masonry-layout

### ISSUE THREAD

**Issue by yoda98mnt** [thomasloven/lovelace-layout-card#317]
My Home Assistant version: 2025.05.2

Layout-card version (FROM BROWSER CONSOLE): v.2.4.6

What I am doing: start the lovelace card

What I expected to happen: showing the card
What happened instead: custom element doesn't exist: masonry-layout error

**Minimal** steps to reproduce:

```yaml
theme: Backend-selected
title: Home
type: custom:masonry-layout
badges: []
cards:
  - square: true
    columns: 5
    type: grid
    cards:
      - show_name: true
        show_icon: true
        type: button
        tap_action:
          action: navigate
          navigation_path: /lovelace/energie
        icon: mdi:home-lightning-bolt
        name: Energie
      - show_name: true
        show_icon: true
        type: button
        tap_action:
          action: navigate
          navigation_path: /lovelace/heizung
        icon: mdi:heating-coil
        name: Heizen
      - show_name: true
        show_icon: true
        type: button
        tap_action:
          action: navigate
          navigation_path: /lovelace-kiosk
        icon: mdi:home
        name: Home
      - show_name: true
        show_icon: true
        type: button
        tap_action:
          action: call-service
          service: switch.turn_on
          data: {}
          target:
            device_id: 82865dc4fe4d991d7010e95a75276131
        entity: binary_sensor.garagentor2_status
        name: Tor
      - show_name: true
        show_icon: true
        type: button
        tap_action:
          action: navigate
          navigation_path: /lovelace/test2
        icon: mdi:robot-vacuum
        name: Reinigen
  - type: markdown
    content: >
      #### Nächster Abfall-Termin


      ***


      ####
      {{states.sensor.abholung_nachster.attributes.values()|first}}:{{states.sensor.abholung_nachster.attributes|first|as_timestamp|timestamp_custom("
      %d.%m.%Y")}}


      ***

      <font color='#44739E'><ha-icon icon="mdi:trash-can"></ha-icon></font>
      Restmüll:&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; {% if
      has_value('sensor.restmull') %}
      {{states.sensor.restmull.attributes|first|as_timestamp|timestamp_custom("
      %d.%m.%Y")}} {% else %} kein Termin {%endif %}</th>

      <font color='#44739E'><ha-icon icon="mdi:recycle"></ha-icon></font> Gelber
      Sack:&nbsp;&nbsp;&nbsp; {% if has_value('sensor.gelber_sack') %}
      {{states.sensor.gelber_sack.attributes|first|as_timestamp|timestamp_custom("
      %d.%m.%Y")}} {% else %} kein Termin {%endif %}</th>

      <font color='#44739E'><ha-icon icon="mdi:recycle"></ha-icon></font>
      Papiertonne:&nbsp;&nbsp;&nbsp; {% if has_value('sensor.papier') %}
      {{states.sensor.papier.attributes|first|as_timestamp|timestamp_custom("
      %d.%m.%Y")}} {% else %} kein Termin {%endif %}</td>

      <font color='#44739E'><ha-icon icon="mdi:recycle"></ha-icon></font> Grüne
      Tonne:&nbsp;&nbsp; {% if has_value('sensor.biomull') %}
      {{states.sensor.biomull.attributes|first|as_timestamp|timestamp_custom("
      %d.%m.%Y")}} {% else %} kein Termin {%endif %}</td>
  - show_current: true
    show_forecast: true
    type: weather-forecast
    entity: weather.forecast_home
    name: Wolfsburg Wettervorhersage
  - show_name: true
    show_icon: true
    type: button
    tap_action:
      action: call-service
      service: browser_mod.popup
      data:
        content:
          type: entities
          entities:
            - entity: binary_sensor.fensterkontakt_schlafzimmer_state
              name: Schlafzimmerfenster
            - entity: binary_sensor.tuerkontakt_wohnzimmer_ost_state
              name: Wohnzimmer Tür Ost
            - entity: binary_sensor.tuerkontakt_wohnzimmer_sued_state
              name: Wohnzimmer Tür Süd
            - entity: binary_sensor.fensterkontakt_kinderzimmer
              name: Yannick Fenster
          state_color: true
        title: Fenster
      target: {}
    name: Fenster offen / geschlossen
    entity: binary_sensor.tuerkontakt_gruppe
    icon: mdi:window-closed-variant
    icon_height: 75px
  - type: markdown
    content: >
      #### Nächster Geburtstag 


      ***

      {{ states.calendar.geburtstage.attributes.message }} <font
      color='#44739E'><ha-icon icon="mdi:party-popper"></ha-icon></font>


      am
      {{states.calendar.geburtstage.attributes.start_time|as_timestamp|timestamp_custom("
      %d.%m.%Y") }}

      ***
  - type: custom:digital-clock
    dateFormat:
      weekday: long
      day: 2-digit
      month: long
    timeFormat:
      hour: 2-digit
      minute: 2-digit
    card_mod:
      style: |
        ha-card {
          font-size: 15px;
        }
        .span.value {
          font-size: 27px;
        }
  - type: custom:apexcharts-card
    apex_config:
      legend:
        show: false
    graph_span: 7d
    span:
      end: day
    header:
      show: true
      title: Täglich Energieumsatz der letzten sieben Tage
      show_states: true
      colorize_states: true
      standard_format: false
    color_list:
      - red
      - green
      - yellow
    series:
      - entity: sensor.stromverbrauch_kwh
        name: Heute verbrauchte Energi
        type: column
        statistics:
          type: sum
          period: day
        group_by:
          duration: 1d
          start_with_last: true
          func: diff
      - entity: sensor.pv_total_energie_kwh
        name: Heute Erzeugte Energie PV-Anlage
        type: column
        statistics:
          type: sum
          period: day
        group_by:
          duration: 1d
          start_with_last: true
          func: diff
      - entity: sensor.daily_exported_energy
        name: Heute exportierte Energie
        type: column
        statistics:
          type: sum
          period: day
        group_by:
          duration: 1d
          start_with_last: true
          func: diff

# End of code
```

Error messages from the browser console: custom element doesn't exist: masonry-layout

---

**By putting an X in the boxes ([X]) below, I indicate that I:**

- [] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).
- [] Have made sure I am using the latest version of the plugin.
- [] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.
- [] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
