### ISSUE TITLE
No top margin and too small side margins after update HA to 0.99

### ISSUE THREAD

**Issue by bieniu** [thomasloven/lovelace-layout-card#32]
After update HA to 0.99 there is no top margin (space between cards and top panel) with option `panel: true` for view and side margins are too small.

Configuration:
```
- id: energy
    icon: mdi:power-plug
    title: "Energia"
    path: energy
    panel: true
    cards:
      - type: custom:layout-card
        column_width: 290
        cards:
          - ...
          - ...
          - ...
```

HA 0.98 and earliers:
![image](https://user-images.githubusercontent.com/478555/65372284-1fd3d380-dc6e-11e9-9e22-79eca1647a76.png)

HA 0.99
![image](https://user-images.githubusercontent.com/478555/65372291-3712c100-dc6e-11e9-94a5-9915bbe669e9.png)
