### ISSUE TITLE
Version 2.0 breaks thermostat card

### ISSUE THREAD

**Issue by kmlucy** [thomasloven/lovelace-layout-card#37]
When I update from legacy to 2.0, My thermostat card breaks as shown:

![image](https://user-images.githubusercontent.com/13952475/68631725-d0659300-04b9-11ea-9472-c58cd2998534.png)

```
panel: true
cards:
  - type: custom:layout-card
    layout: horizontal
    max_columns: 3
    cards:
      - type: thermostat
        entity: climate.hallway
```
