### ISSUE TITLE
Card Margin

### ISSUE THREAD

**Issue by xMrVizzy** [thomasloven/lovelace-layout-card#38]
<img width="626" alt="CleanShot 2019-11-12 at 19 04 21@2x" src="https://user-images.githubusercontent.com/7906418/68678173-408a1c80-057f-11ea-9bdc-6f264830961d.png">
I have this:

```
- type: horizontal-stack
          cards:
            - !include ../includes/blank-card.yaml
            - type: custom:layout-card
              layout: horizontal
              min_columns: 4
              cards:
                ... button-cards here
            - !include ../includes/blank-card.yaml
```

If I disable root margin it looks like it should be:
![CleanShot 2019-11-12 at 19 07 42@2x](https://user-images.githubusercontent.com/7906418/68678468-ce660780-057f-11ea-89cb-14d3e8f8412d.png)

How I can modify lovelace-layout-card margin using lovelace-card-mod style?
