### ISSUE TITLE
TypeError: n is undefined

### ISSUE THREAD

**Issue by PurelyNicole** [thomasloven/lovelace-layout-card#40]
I am seeing this error frequently in my Home Assistant logs. It is triggered on page load in Firefox only.

`ERROR (MainThread) [frontend.js.latest.201911195] https://my_ip/community_plugin/lovelace-layout-card/layout-card.js:1:7493 TypeError: n is undefined`

In Chrome, I get a similar error when navigating away from the page. In that case, I get:

`ERROR (MainThread) [frontend.js.latest.201911195] https://my_ip/community_plugin/lovelace-layout-card/layout-card.js:1:7495 Uncaught TypeError: Cannot read property 'appendChild' of undefined`

This is my card configuration, it is viewed in Panel Mode:

```yaml
cards:
  - cards:
      - entity: weather.dark_sky
        type: weather-forecast
      - entities:
          - entity: person.nicole
          - entity: person.eric
        title: Presence
        type: glance
      - entities:
          - entity: light.hallway_lights
            name: Hallway
            show_state: false
            tap_action:
              action: toggle
          - entity: switch.entryway_light_switch
            name: Entry
            show_state: false
            tap_action:
              action: toggle
          - entity: lock.front_door_lock_locked
            name: Front Door
            show_state: false
        title: Entryway
        type: glance
      - entities:
          - entity: switch.peninsula_light_switch
            name: Peninsula
            tap_action:
              action: toggle
          - entity: switch.under_cabinet_lights_switch
            name: Cabinets
            tap_action:
              action: toggle
          - entity: light.kitchen_overhead_lights
            name: Overhead
          - entity: lock.kitchen_door_lock_locked
            name: Door
            tap_action:
              action: toggle
          - entity: binary_sensor.kitchen_patio_door_motion_sensor
            name: Patio Door
        show_state: false
        title: Kitchen
        type: glance
      - entities:
          - entity: switch.guest_room_floor_lamp_switch
            name: Guest Room Floor
            tap_action:
              action: toggle
          - entity: switch.guest_room_nightstand_lamp_switch
            name: Guest Room Table
            tap_action:
              action: toggle
          - entity: light.gym_light_switch
            name: Gym
            tap_action:
              action: toggle
          - entity: light.dining_room_light
            name: Dining Room
            tap_action:
              action: toggle
        show_state: false
        title: Other Rooms
        type: glance
      - break
      - entities:
          - entity: switch.bar_lights_switch
            name: Bar
            show_state: false
            tap_action:
              action: toggle
          - entity: switch.fireplace_lights_switch
            name: Fireplace
            show_state: false
            tap_action:
              action: toggle
          - entity: switch.globe_lamp_switch
            name: Globe Lamp
            show_state: false
            tap_action:
              action: toggle
          - entity: switch.table_lamps_switch
            name: Table Lamps
            show_state: false
            tap_action:
              action: toggle
          - entity: switch.fish_light
            name: Fish Tank
            show_state: false
            tap_action:
              action: toggle
          - entity: binary_sensor.living_room_door_sensor
            name: Patio Door
            show_state: false
            tap_action:
              action: toggle
          - entity: sensor.living_room_thermostat_temperature
            name: Temperature
            tap_action:
              action: toggle
          - entity: sensor.living_room_thermostat_humidity
            name: Humidity
          - entity: sensor.living_room
            name: Activity
        show_state: true
        title: Living Room
        type: glance
      - entities:
          - entity: light.bedroom_entry_light
            name: Entry
            show_state: false
            tap_action:
              action: toggle
          - entity: light.bedroom_light_switch
            name: Overhead
            show_state: false
            tap_action:
              action: toggle
          - entity: light.bathroom_vanity_light
            name: Vanity
            show_state: false
            tap_action:
              action: toggle
          - entity: light.bathroom_shower
            name: Shower
            show_state: false
            tap_action:
              action: toggle
          - entity: sensor.bedroom_temperature
            name: Temperature
          - entity: sensor.bedroom_humidity
            name: Humidity
        show_state: true
        title: Bedroom
        type: glance
      - entities:
          - entity: fan.loft_ceiling_fan
            name: Fan
            show_state: false
            tap_action:
              action: toggle
          - entity: light.loft_fan_light
            name: Fan Light
            show_state: false
            tap_action:
              action: toggle
          - entity: switch.tetris_lamp_switch
            name: Tetris Lamp
            show_state: false
            tap_action:
              action: toggle
          - entity: switch.reading_lamp_switch
            name: Reading Lamp
            show_state: false
            tap_action:
              action: toggle
          - entity: light.desk_light_switch
            name: Desk
            show_state: false
            tap_action:
              action: toggle
          - entity: light.alcove_light_switch
            name: Alcove
            show_state: false
            tap_action:
              action: toggle
          - entity: sensor.record_console_temperature
            name: Temperature
          - entity: sensor.record_console_relative_humidity
            name: Humidity
        show_state: true
        title: Loft
        type: glance
      - break
      - entities:
          - entity: switch.deck_flood_lights_switch
            name: Flood
            show_state: false
            tap_action:
              action: toggle
          - entity: switch.garage_flood_lights_switch
            name: Garage
            show_state: false
            tap_action:
              action: toggle
          - entity: switch.landscaping_lights_switch
            name: Landscaping
            show_state: false
            tap_action:
              action: toggle
          - entity: switch.patio_flood_lights_switch
            name: Patio
            show_state: false
            tap_action:
              action: toggle
          - entity: light.pier_lights
            name: Pier
            show_state: false
            tap_action:
              action: toggle
          - entity: switch.porch_light_switch
            name: Porch
            show_state: false
            tap_action:
              action: toggle
          - entity: switch.workshop_light_switch
            name: Workshop
            show_state: false
            tap_action:
              action: toggle
          - entity: cover.garage_door
            name: Garage
            show_state: false
            tap_action:
              action: toggle
        title: Outdoor
        type: glance
      - entities:
          - entity: lock.workshop_door_lock_locked
            name: Lock
            show_state: false
            tap_action:
              action: toggle
          - entity: sensor.workshop_temperature
            name: Temperature
          - entity: sensor.workshop_humidity
            name: Humidity
        title: Workshop
        type: glance
      - dateBottomFormat: ddd
        dateTopFormat: DD
        entities:
          - calendar.nicoles_calendar
          - calendar.eric_nicole_events
          - calendar.eric_events
        eventsLimit: '99'
        hideHeader: false
        hidePastEvents: false
        hideTime: false
        highlightToday: false
        ignoreEventsByLocationExpression: ''
        ignoreEventsExpression: ''
        numberOfDays: '7'
        progressBar: false
        showEventOrigin: false
        showLocation: false
        showLocationIcon: true
        showMultiDay: false
        startFromToday: false
        timeFormat: 'HH:mma'
        type: 'custom:calendar-card'
    layout: vertical
    type: 'custom:layout-card'
  - break
  - cards:
      - aspect_ratio: 0%
        camera_image: camera.driveway_cam2
        camera_view: live
        entities:
          - entity: camera.driveway_cam2
        type: picture-glance
      - aspect_ratio: 0%
        camera_image: camera.porch
        camera_view: live
        entities:
          - entity: camera.porch
        entity: camera.porch
        type: picture-glance
      - aspect_ratio: 0%
        camera_image: camera.ind
        entity: camera.ind
        show_name: false
        show_state: false
        type: picture-entity
    column_width: 100%
    layout: vertical
    max_columns: 1
    min_columns: 1
    type: 'custom:layout-card'
column_width:
  - 75%
  - 25%
layout: vertical
max_columns: 2
min_columns: 2
type: 'custom:layout-card'
```
