### ISSUE TITLE
Responsive design not working on small screen

### ISSUE THREAD

**Issue by aukedejong** [thomasloven/lovelace-layout-card#44]
Hi,
I just updated your plugin. It seams something changed, maybe bug. I'm not sure how to fix it.

Using this config:
```
      column_width: 200
      layout: vertical
      max_width:
        - 30%
        - 30%
        - 30%
        - 10%
      rebuild: 100
      type: 'custom:layout-card'
```
With tab config panel: true
It works fine until I make the screen width smaller.
It looks like it keeps the 4 column, when I get to phone width, around 400px. So I get one column filled with cards, with the width of 1/4 of the screens width. 

An older versions doesn't have this problem.
This commit works for me:
```
Author: Thomas Lov<C3><A9>n <thomasloven@gmail.com>
Date:   Wed Apr 24 13:52:29 2019 +0200
    fix typo
```

Thanks for the great work.
