### ISSUE TITLE
All my cards display in one column

### ISSUE THREAD

**Issue by antoineguilbert** [thomasloven/lovelace-layout-card#46]
Hi,

I've copy/paste the example but all my cards are stuck in only one column. 
I've tried to clear my browser cache on Google Chrome and Apple Safari. 

<img width="672" alt="Capture d’écran 2020-01-08 à 21 24 01" src="https://user-images.githubusercontent.com/16510381/72012988-46d60580-325d-11ea-816b-b38785e23273.png">

My config 

```
type: 'custom:layout-card'
cards:
  - type: entities
    title: 1
    entities:
      - light.bureau
  - type: entities
    title: 2
    entities:
      - light.bureau
  - break
  - type: entities
    title: 3
    entities:
      - light.bureau
  - type: entities
    title: 4
    entities:
      - light.bureau
      - light.bureau
      - light.bureau
      - light.bureau
  - type: entities
    title: 5
    entities:
      - light.bureau

```
Thanks a lot.
