### ISSUE TITLE
When using "type: conditional" there is a blank space

### ISSUE THREAD

**Issue by jonostanck** [thomasloven/lovelace-layout-card#5]
When I use `custom:layout-card` and its child is `- type: conditional` and condition is not met resulting in not showing card from this condition there is a blank space (columns are populated with: `<hui-conditional-card style="display: none;"></hui-conditional-card>` which should not be taken into cosideration as a card).

If you could do something about it I would very much appreciate it :) thanks

**Comment by thomasloven** [comment]
Is this still a problem with the latest version of layout-card?

**Comment by jonostanck** [comment]
I have changed parts of the problematic yaml many days ago but after testing this now it seems to be fixed. Thanks :)

**Comment by thomasloven** [comment]
Excelent!
Thank you for taking the time to check it!

**Comment by nielsfaber** [comment]
I am having exactly the same issue, it does not seem fixed.
Conditional card with conditions not met, results in `<hui-conditional-card style="display: none;"></hui-conditional-card>`. The card is wrapped inside an `<div class="column"></div>`, which gives an empty space in the grid.

**Comment by rccoleman** [comment]
I've started seeing exactly this issue when I added two conditional cards to an existing horizontal layout of 7 button cards.  Depending on the conditions, either 1 or none of the conditional cards should be visible, and I always end up with a blank space in the layout when one of them is visible and the other is not.  If neither is visible or both are visible, the layout is as-expected.  As above, you I get a "display: none" in the element picker:

<img width="627" alt="Screen Shot 2020-07-06 at 11 40 06 AM" src="https://user-images.githubusercontent.com/860888/86627655-874cdc80-bf7d-11ea-8195-a9b392e938e9.png">

Example:

<img width="964" alt="Screen Shot 2020-07-06 at 11 44 55 AM" src="https://user-images.githubusercontent.com/860888/86628056-2a9df180-bf7e-11ea-9dc1-f580402459bf.png">

Card snippet:

```
                # type: horizontal-stack
                type: custom:layout-card
                layout: horizontal
                min_columns: 9
                max_width: 150px
                min_height: 100px
                cards:
                - type: conditional
                  card:
                    type: "custom:button-card"
                    entity: sensor.landscape
                    template: badge_template_desktop
                    name: Landscape
                    icon: "mdi:pine-tree"
                    show_name: true
                    show_state: false
                    state:
                      - value: "0"
                        color: red
                      - value: "1"
                        color: green
                  conditions:
                    - entity: sensor.landscape
                      state_not: '2'
                - type: conditional
                  card:
                    type: "custom:button-card"
                    entity: sensor.recyling
                    template: badge_template_desktop
                    name: Recycling
                    icon: "mdi:recycle"
                    show_name: true
                    show_state: false
                    state:
                      - value: "0"
                        color: red
                      - value: "1"
                        color: green
                  conditions:
                    - entity: sensor.recycling
                      state_not: '2'
```

Changing the `min_columns:` to smaller values also seems to move the buttons around in unexpected ways - making it 5, 6, or 7 creates a new row (expected), but the icon directly below the blank space is rendered in the blank space, and the blank space ends up below:

<img width="733" alt="Screen Shot 2020-07-06 at 11 51 20 AM" src="https://user-images.githubusercontent.com/860888/86628639-07c00d00-bf7f-11ea-8bcd-64437f86f307.png">

A regular `horizontal-stack` displays the button correctly regardless of whether the conditional cards are visible, but it offers considerably less flexibility in card layout.  I was about to open a new issue, but this is exactly what I'm seeing and decided to comment here for now.  I'm happy to open a new issue if you'd prefer.

I'm using v16 of the layout card, the latest from HACS.
