### ISSUE TITLE
Layout is verticle until I go to another view

### ISSUE THREAD

**Issue by shauder** [thomasloven/lovelace-layout-card#51]
The problem I am having is similar to the cast issue you have noted except I seem to have it in just the regular browser (FireFox and Chrome).

The page loads as I would expect except that everything is in one vertical stack. When I go to another view then I can see it all flatten out as it is switching to the other view. Then when I click back it all is horizontal like I would expect.

Another thing to note is if I start on another view then go to this view then it is not correct.  I still have to navigate away then come back.

The after is what I would expect it to look like. After playing around with it a bit it seems to fix itself to the horizontal with any adjustment to the browser size. So I wonder if lovelace_gen is making it think it doesn't need as much width as it does?

I also just found out I can just click the overview button again and it will re-format horizontally. 

```
# Lovelace Resources
resources:
  !include lovelace2/includes/resources.yaml

custom_header:
  hide_tabs: 0,1,2,3,4,5,6,7,8,9,10,11,12
  button_text:
    options: >-
      {{ hours12 }}:{{ minutesLZ }} {{ ampm }} - <ha-icon icon='mdi:weather-{{
      states.weather.dark_sky.state }}'></ha-icon> {{
      states.weather.dark_sky.attributes.temperature }}°
  compact_mode: true

# Views
# ui-lovelace.yaml
title: Home
background: var(--background-image)
views:
  # - !include_dir_merge_named lovelace/views/
  - !include lovelace2/views/homekit.yaml
  - !include lovelace2/views/main.yaml

```

```
# resources.yaml
# HomeKit card/layout
- url: /community_plugin/Homekit-panel-card/homekit-panel-card.js
  type: module

# Popup cards
- url: /community_plugin/light-popup-card/light-popup-card.js
  type: module
- url: /community_plugin/thermostat-popup-card/thermostat-popup-card.js
  type: module
- url: /community_plugin/media_player-popup-card/media_player-popup-card.js
  type: module

- url: /community_plugin/button-card/button-card.js
  type: module


- url: /community_plugin/lovelace-layout-card/layout-card.js
  type: module
- url: /community_plugin/lovelace-auto-entities/auto-entities.js
  type: module
- url: /community_plugin/lovelace-card-mod/card-mod.js
  type: module
- url: /community_plugin/lovelace-card-tools/card-tools.js
  type: module
- url: /community_plugin/lovelace-fold-entity-row/fold-entity-row.js
  type: module
- url: /community_plugin/lovelace-more-info-card/more-info-card.js
  type: module
```

```
# lovelace_gen
# main.yaml
title: "Home"
path: "home"
panel: true
# popup_cards: !include 
#   - ../includes/popups.yaml
#   - homekit_light: {{ _global.all_lights }}
#     homekit_climate: {{ _global.all_climate_thermostats }}
cards:
  - type: custom:layout-card
    cards:
      {% for room in _global.rooms %}
      - type: vertical-stack
        cards:
          - type: markdown
            style: |
              ha-card {
                box-shadow: none;
                height: 33px;
                background: none;
                padding: 0px 11px;
                color: var(--header-color);
              }
            content: >
              ##### {{ room | replace("_", " ") }}
          - type: custom:auto-entities
            card:
              type: custom:layout-card
              min_columns: 3
              max_columns: 3
              justify_content: start
              layout: horizontal
            filter:
              include:
                - entity_id: "light.{{ room | replace("_bedroom", "")  }}*"
                  sort:
                    method: name
                  options:
                    type: custom:button-card
                    aspect_ratio: {{ aspect_ratio|default('1/1') }}
                    size: {{ size|default('25%') }}
                    show_name: {{ show_name|default('true') }}
                    show_icon: {{ show_icon|default('true') }}
                    show_state: {{ show_state|default('true') }}
                    show_label: {{ show_label|default('true') }}
                    styles:
                      card:
                        - border-radius: "14px"
                        - --ha-card-background: "var(--card-color-off)"
                        - box-shadow: "2px 2px 2px 0px rgba(0,0,0,0.75)"
                    tap_action: 
                      action: {{ tap_action|default('toggle') }}
                      haptic: light
                    hold_action:
                      action: {{ hold_action|default('call-service') }}
                      service: browser_mod.popup
                      service_data:
                        title: ' '
                        style:
                          background: rgba(0, 0, 0, 0.5)
                          "--iron-icon-fill-color": "#FFF"
                          "--iron-icon": "#FFF"
                          color: white !important
                        card:
                          type: vertical-stack
                          cards:
                            - !include
                              - {{ template|default('../templates/switch_popup.yaml') }}
                              - entity: this.entity_id
                        deviceID:
                          - this
                      haptic: heavy
                - entity_id: "binary_sensor.contact_{{ room | replace("_bedroom", "")  }}*"
                  sort:
                    method: name
                  options:
                    type: custom:button-card
                    aspect_ratio: {{ aspect_ratio|default('1/1') }}
                    size: {{ size|default('25%') }}
                - entity_id: "binary_sensor.motion_{{ room | replace("_bedroom", "")  }}*"
                  sort:
                    method: name
                  options:
                    type: custom:button-card
                    aspect_ratio: {{ aspect_ratio|default('1/1') }}
                    size: {{ size|default('25%') }}
                - type: custom:button-card
                  color_type: blank-card
                  aspect_ratio: 1/1
                - type: custom:button-card
                  color_type: blank-card
                  aspect_ratio: 1/1
              exclude:
                - name: "{{ room | replace("_bedroom", "") | capitalize }}*"
                - name: "{{ room | replace("_room", "") | capitalize }}*"
          {% endfor %}
```

Before:
![before](https://user-images.githubusercontent.com/1296766/72952116-840abf00-3d56-11ea-8c0e-4bc2a7efd006.PNG)
After:
![after](https://user-images.githubusercontent.com/1296766/72952125-8836dc80-3d56-11ea-8721-692d089945ae.PNG)

**Comment by thomasloven** [comment]
Could you please try version 10 and see if that fixes it?

**Comment by shauder** [comment]
Looks like I am still experiencing the same issue after upgrading to 10.  I am using the !file macro from lovelace_gen so it should not be caching the old version.

**Comment by shauder** [comment]
I got some time to try it without lovelace_gen and without auto-entities and am seeing the same issue it seems.

First load:
<img width="1423" alt="Screen Shot 2020-02-13 at 11 20 44 AM" src="https://user-images.githubusercontent.com/1296766/74460845-306e2b80-4e53-11ea-8e4d-303485dddda8.png">

After I change screens or change the size of the window or click on the "Overview" button again:
<img width="1420" alt="Screen Shot 2020-02-13 at 11 20 49 AM" src="https://user-images.githubusercontent.com/1296766/74460862-38c66680-4e53-11ea-8315-5bf09ffc93d2.png">


Code:
```
title: "Home"
path: "home"
panel: true
cards:
  - type: custom:layout-card
    max_columns: 3
    max_width: 600px;
    cards:
      - type: vertical-stack
        cards:
          - type: markdown
            style: |
              ha-card {
                --paper-card-background-color: 'rgba(11, 11, 11, 0.00)';
                box-shadow: 2px 2px rgba(0,0,0,0.0);
              }
              h1 {
                font-size: 24px;
                font-weight: bold;
                font-family: Helvetica;
                letter-spacing: '0.01em';
                color: rgb(180, 225, 250);
              }
            content: |
              # Test
          - type: custom:layout-card
            min_columns: 3
            max_columns: 3
            justify_content: start
            layout: horizontal
            cards:
              - !include ../templates/button.yaml
              - !include ../templates/button.yaml
              - !include ../templates/button.yaml
      - type: vertical-stack
        cards:
          - type: markdown
            style: |
              ha-card {
                --paper-card-background-color: 'rgba(11, 11, 11, 0.00)';
                box-shadow: 2px 2px rgba(0,0,0,0.0);
              }
              h1 {
                font-size: 24px;
                font-weight: bold;
                font-family: Helvetica;
                letter-spacing: '0.01em';
                color: rgb(180, 225, 250);
              }
            content: |
              # Test
          - type: custom:layout-card
            min_columns: 3
            max_columns: 3
            justify_content: start
            layout: horizontal
            cards:
              - !include ../templates/button.yaml
              - !include ../templates/button.yaml
              - !include ../templates/button.yaml
      - type: vertical-stack
        cards:
          - type: markdown
            style: |
              ha-card {
                --paper-card-background-color: 'rgba(11, 11, 11, 0.00)';
                box-shadow: 2px 2px rgba(0,0,0,0.0);
              }
              h1 {
                font-size: 24px;
                font-weight: bold;
                font-family: Helvetica;
                letter-spacing: '0.01em';
                color: rgb(180, 225, 250);
              }
            content: |
              # Test
          - type: custom:layout-card
            min_columns: 3
            max_columns: 3
            justify_content: start
            layout: horizontal
            cards:
              - !include ../templates/button.yaml
              - !include ../templates/button.yaml
              - !include ../templates/button.yaml
```

**Comment by shauder** [comment]
After messing around with this some more I think I have narrowed the issue down to nested layout-cards?

This does what I would expect
```
# lovelace_gen
title: "Home"
path: "home"
panel: true
cards:
  - type: custom:layout-card
    min_columns: 3
    max_columns: 6
    max_width: 300px;
    cards:
      - !include ../templates/button.yaml
      - !include ../templates/button.yaml
      - !include ../templates/button.yaml
      - !include ../templates/button.yaml
      - !include ../templates/button.yaml
      - !include ../templates/button.yaml
      - !include ../templates/button.yaml
      - !include ../templates/button.yaml
      - !include ../templates/button.yaml
```

But then when I had the sub-layout-cards it goes back to the vertical stack until I move the window, etc...

```
# lovelace_gen
title: "Home"
path: "home"
panel: true
cards:
  - type: custom:layout-card
    min_columns: 3
    max_columns: 3
    max_width: 600px;
    cards:
      - type: custom:layout-card
        min_columns: 3
        max_columns: 3
        justify_content: start
        layout: horizontal
        cards:
          - !include ../templates/button.yaml
          - !include ../templates/button.yaml
          - !include ../templates/button.yaml
      - type: custom:layout-card
        min_columns: 3
        max_columns: 3
        justify_content: start
        layout: horizontal
        cards:
          - !include ../templates/button.yaml
          - !include ../templates/button.yaml
          - !include ../templates/button.yaml
      - type: custom:layout-card
        min_columns: 3
        max_columns: 3
        justify_content: start
        layout: horizontal
        cards:
          - !include ../templates/button.yaml
          - !include ../templates/button.yaml
          - !include ../templates/button.yaml
```
