### ISSUE TITLE
- break does not work properly

### ISSUE THREAD

**Issue by kajmaj** [thomasloven/lovelace-layout-card#53]
[https://github.com/thomasloven/lovelace-layout-card#--break](url) seems to be not working

I have lovelace-layout card installed via HACS

```
resources:
  - url: /local/community/lovelace-layout-card/layout-card.js
    type: module
```

use following lovelace config:
```
- title: "Počasí"
  icon: mdi:weather-sunset
  type: custom:layout-card
  cards:
    - type: weather-forecast
      entity: weather.dark_sky
      name: "Počasí dnes"
    - break
    - type: glance   
      title: "Místní počasí"
      entities:
```
and seeing this:

![image](https://user-images.githubusercontent.com/37018655/73726975-d8d40f80-4730-11ea-925d-1d19eee57490.png)

Did I miss anything?

**Comment by Gibby** [comment]
I am having the same issue.

**Comment by Gibby** [comment]
Figured it out, I was putting it in the wrong place.

**Comment by kajmaj** [comment]
Could you be so kind to be more specific?
Odesláno ze zařízení Alcatel Onetouch Device

**Comment by Gibby** [comment]
@kajmaj I was trying to use break right under the first card option, instead of under the layout-card

**Comment by colemamd** [comment]
I have the same issue as well. Sounds like Gibby's issue was indentation. When my indentation is off, Lovelace throws an error and doesn't load at all. When my indentation is correct, I get the same error you are reporting ("Config is not an object).

**Comment by kajmaj** [comment]
@colemamd  I solved it finally. My problem was wrong location of `type: custom:layout-card`
I add `panel: true` and changed indentation - all is fine now. 

before:
```
- title: "Počasí"
  icon: mdi:weather-sunset
  type: custom:layout-card
  cards:
```

after:
```
- title: "Počasí"
  icon: mdi:weather-sunset
  panel: true
  cards:
  - type: custom:layout-card
    layout: vertical
    cards:
```
