### ISSUE TITLE
not work correcly

### ISSUE THREAD

**Issue by davide-rhw** [thomasloven/lovelace-layout-card#54]
hi i add correctly file js into ww path and to ui file yaml.

I want this single card full screen but not work:

```
  - icon: 'mdi:server'
    panel: true
    path: pc
    title: PC
    badges: []
    type: 'custom:layout-card'
    gridcols: 6
    gridrows: 6
    cards:
      - entities:
          - entity: switch.accensione_workstationdav
          - entity: switch.momentary_workstation_davide_off
          - entity: binary_sensor.worstation_davide
        show_header_toggle: false
        title: Workstation
        type: entities
```

**Comment by shauder** [comment]
Did you set the view to panel mode?
```
title: "Home"
path: "home"
panel: true
cards:
  - icon: 'mdi:server'
    panel: true
    path: pc
    title: PC
    badges: []
    type: 'custom:layout-card'
    gridcols: 6
    gridrows: 6
    cards:
      - entities:
          - entity: switch.accensione_workstationdav
          - entity: switch.momentary_workstation_davide_off
          - entity: binary_sensor.worstation_davide
        show_header_toggle: false
        title: Workstation
        type: entities
```
