### ISSUE TITLE
Is this compatible with config-template-card?

### ISSUE THREAD

**Issue by coenboomkamp** [thomasloven/lovelace-layout-card#55]
Hi there!

Loving the plugin, just what i was looking for thanks!

Problem is that i can't get it to work with a [config-template-card](https://github.com/iantrich/config-template-card), i use it to change icons based on a state.

Here is the normal config of such a card:

```
card:
  columns: 2
  entities:
    - entity: input_boolean.sk_raam_links
      icon: >-
        ${states['input_boolean.sk_raam_links'].state === 'on' ?
        'mdi:window-open-variant' : 'mdi:window-closed-variant'}
      name: Links
    - entity: input_boolean.sk_raam_rechts
      icon: >-
        ${states['input_boolean.sk_raam_rechts'].state === 'on' ?
        'mdi:window-open-variant' : 'mdi:window-closed-variant'}
      name: Rechts
  show_name: true
  show_state: false
  title: Ramen
  type: 'custom:hui-glance-card'
entities:
  - input_boolean.sk_raam_links
  - input_boolean.sk_raam_rechts
type: 'custom:config-template-card'
variables:
  - 'states[''input_boolean.sk_raam_links''].state'
  - 'states[''input_boolean.sk_raam_rechts''].state'
```

Now i'm trying to get this working in your layout-card, but so far without any luck, this is my config:
```
column_width: 200
layout: vertical
max_width: 100%
rebuild: 100
type: 'custom:layout-card'
cards:
  - type: 'custom:hui-glance-card'
    columns: 2
    entities:
      - entity: input_boolean.sk_raam_links
        icon: >-
          ${states['input_boolean.sk_raam_links'].state === 'on' ?
          'mdi:window-open-variant' : 'mdi:window-closed-variant'}
        name: Links
      - entity: input_boolean.sk_raam_rechts
        icon: >-
          ${states['input_boolean.sk_raam_rechts'].state === 'on' ?
          'mdi:window-open-variant' : 'mdi:window-closed-variant'}
        name: Rechts
    show_name: true
    show_state: false
    title: Ramen
  - type: 'custom:config-template-card'
    entities:
      - input_boolean.sk_raam_links
      - input_boolean.sk_raam_rechts
    variables:
      - 'states[''input_boolean.sk_raam_links''].state'
      - 'states[''input_boolean.sk_raam_rechts''].state'
```

Any ideas?

Thanks sofar!
