### ISSUE TITLE
entity: group.exmple does not show status

### ISSUE THREAD

**Issue by noname-ever** [thomasloven/lovelace-layout-card#56]
Hello.

Can you please implement support for group entities to show their status? Currently if I make a group of switches for rooms I can successfully control but have no visual indication about the status of the lights.

This is my Groups.yaml file:
```yaml
  miegamasis:
    name: Miegamasis
    entities:
      - switch.shelly_shsw_25_8caab5057b7a_1
      - switch.shelly_shsw_25_8caab5057b7a_2
```
This is my cards config:
```yaml
cards:
  - cards:
      - entities: null
        entity: group.miegamasis
        icon: 'mdi:bed-empty'
        name: Miegamasis
        type: button
      - entities: null
        entity: switch.shelly_shsw_25_8caab5057b7a_1
        icon: 'mdi:human-greeting'
        name: 1 lempa
        type: entity-button
    type: horizontal-stack
layout: vertical
type: 'custom:layout-card'
```
In the picture you can see that if I add only one entity, the status is shown:
![image](https://user-images.githubusercontent.com/60624891/75631477-f09d9700-5bfb-11ea-88b7-c4b0f3fd5435.png)
