### ISSUE TITLE
History Graph Card (history-graph) not updating when layout-card is used

### ISSUE THREAD

**Issue by radoslavsirota** [thomasloven/lovelace-layout-card#58]
Hello, 
 originaly I thought it is an frontend issue (https://github.com/home-assistant/frontend/issues/5129) but after some testing I narrowed it down to layout-card. When I use it in my configuracion, history-graph does not update in time. All other cards (at least those I use) work well. Could you please have a look at it?

```
title: Home
views:
  - id: dashboard
    path: dashboard
    icon: 'mdi:home-assistant'
    panel: true
    title: 'Dashboard'
    badges: []
    cards:
    - type: custom:layout-card
      layout: vertical
      cards:
      - type: vertical-stack
        cards:
        - entities:
            - entity: sensor.bedroom_temperature
              name: 'Spálňa'
            - entity: sensor.kids_room_temperature
              name: 'Detská izba'
            - entity: sensor.paincave_temperature
              name: 'Pracovňa'
            - entity: sensor.dining_room_temperature
              name: 'Obývačka'
            - entity: sensor.master_bathroom_temperature
              name: 'Kúpelňa'
            - entity: sensor.guest_bathroom_temperature
              name: 'Hosťovská kúpelňa'
            - entity: sensor.bedroom_humidity
              name: 'Spálňa'
            - entity: sensor.kids_room_humidity
              name: 'Detská izba'
            - entity: sensor.paincave_humidity
              name: 'Pracovňa'
            - entity: sensor.dining_room_humidity
              name: 'Obývačka'
            - entity: sensor.master_bathroom_humidity
              name: 'Kúpelňa'
            - entity: sensor.guest_bathroom_humidity
              name: 'Hosťovská kúpelňa'
          hours_to_show: 8
          refresh_interval: 30
          title: 'Teplota a vlhkosť'
          type: history-graph
```
