### ISSUE TITLE
Not working in 0.86 HA version

### ISSUE THREAD

**Issue by wiuwiu** [thomasloven/lovelace-layout-card#6]
Hi.
Ufortunatelly, after upgrading HA to 0.86 version lovelace-layout-card not working. There is no errors in HA log but layout-card doesn't appear and entities which belongs to it also don't appear. Even if i cleared the browser cache.

My config:
```
              - type: entities
                title: 'Dom'
                show_header_toggle: false
                entities:
                  # tryb karmienia
                  - type: custom:fold-entity-row
                    open: true
                    head:
                      type: section
                      label: 'Obsługa trybu karmienia'
                    items:
                      - automation.home_feed_mode_on
                      - automation.home_feed_mode_off_timer
                      - input_boolean.feed_mode_use_mobile
                      - input_boolean.feed_mode_use_notify
                      - input_boolean.feed_mode_use_tts
```
