### ISSUE TITLE
Home assistant 107.6 config is not an object

### ISSUE THREAD

**Issue by gbdavidx** [thomasloven/lovelace-layout-card#62]
In between two cards i have a break, on the front end i have a red box that says config is not an object

```
resources:
  - url: /local/custom-lovelace/upcoming-media-card/upcoming-media-card.js
    type: js
  - url: /local/layout-card.js
    type: module


views:
  - type: custom:layout-card
    layout: vertical
    cards:
        - type: thermostat
          entity: climate.main_floor
        - break
        - type: 'custom:upcoming-media-card'
          entity: sensor.plex_recently_added
          title: Recently Downloaded
          image_style: fanart
```
https://imgur.com/rRiRqDh
