### ISSUE TITLE
Repeated view recomputation with horizontal layout-card in vertical-stack

### ISSUE THREAD

**Issue by crowbarz** [thomasloven/lovelace-layout-card#63]
I'm embedding a layout-card in a vertical stack in my config. From layout-card v12 onwards, the layout card is causing the horizontal and vertical scroll bars to repeatedly appear and disappear, causing the whole page to "shudder" as the layout is repeatedly recomputed. It eventually stops, but that seems to be due to hitting a frontend limit as the following log entry appears:

2020-03-28 21:48:50 ERROR (MainThread) [frontend.js.latest.202001303] https://hass:8123/lovelace/home-test:0:0 ResizeObserver loop limit exceeded

I have replicated and simplified my config to try and isolate the issue, such that the test config uses only standard cards and the layout-card. The goal of the config is to make the top card is full-width, and the bottom card with two columns of cards that are of different widths.
```
  - badges: []
    cards:
      - cards:
          - entity: weather.dark_sky_summary
            type: weather-forecast
          - cards:
              - entities:
                  - entity: sun.sun
                title: "Bottom Left"
                type: entities
              - entities:
                  - entity: sun.sun
                title: "Bottom Right"
                type: entities
            layout: horizontal
            max_width: 1000
            min_width:
              - 55%
              - 45%
            type: 'custom:layout-card'
        type: vertical-stack
    icon: 'mdi:home'
    panel: true
    path: home-test
    title: Home-test
```
Removing the outer vertical-stack leaving only layout-card also stops the shuddering as well.

**Comment by soloam** [comment]
I was going to report the same problem

This is my config with the same problem, this only happens if the vertical scroll is not needed, if the content of the cards fits in the current window

```
title: Suite
icon: mdi:toilet
panel: true
path: suite
cards:
  - type: vertical-stack
    cards:
    - type: custom:layout-card
      layout: horizontal
      max_columns: 2
      max_width: [100%, 100%]
      cards:
        - type: entities
          title: Luzes
          entities:
            - entity: light.suite_light
        - type: entities
          title: Devices
          state_color: true
          entities:
            - entity: switch.suite_fan
        - type: glance
          title: Ambiente
          show_name: false
          entities:
            - sensor.suite_temperature
            - sensor.suite_humidity
```

**Comment by crowbarz** [comment]
I retested this on HA Core 0.107.7 which I just upgraded to, and this issue is still occurring on that release. (I was running 0.105.5 when I logged the issue.)

I hadn't previously tried resizing the window to smaller than the contents as my configuration is supposed to all fit 'above the fold', but in this situation the issue is mitigated with my configuration as well. However, there is a horizontal scrollbar shown when this occurs and I don't remember this being there before.

In case it's browser dependent, I'm using Chrome 81.0.4044.92 (Official Build) beta (64-bit) on macOS 10.14.6. When using Safari on the same computer, the shuddering issue does not occur, although vertical and horizontal scrollbars are always displayed irrespective of whether the contents fit within the window or not.

**Comment by Beertje135** [comment]
same problem here. The flickering is very annoying and prevents me from using controls. I can test if needed. Happy to help if it can solve this problem.
Extra: it seems mostly when I have media_players or graph cards displaying.

**Comment by soloam** [comment]
Anything we can do to help out @thomasloven ? I'm avoiding to redesign my layout to bypass this to keep the test scenario active to make eventual tests, but this is so annoying.

Thank You

**Comment by Dino-Tech** [comment]
I just put the other layout cards inside of this instead of a vertical-stack:
```yaml
              type: custom:layout-card
              layout: vertical
              column_num: 1
              max_width: [100%]
              cards:
```
and seems to work fine as long as padding and margin is set to `0px`
