### ISSUE TITLE
Wrong left and right margins of the view with layout-card

### ISSUE THREAD

**Issue by bieniu** [thomasloven/lovelace-layout-card#64]
With `layout-card` left and right margins of the view are different than without the card. Could it be fixed?

Without `layout-card`:

![image](https://user-images.githubusercontent.com/478555/78119554-e80dcb80-7408-11ea-9af1-9678b3db13d0.png)

With `layout-card`:

![image](https://user-images.githubusercontent.com/478555/78119582-f2c86080-7408-11ea-9e82-cf64c784c5a2.png)

My configuration:
```yaml
- id: climate
    icon: mdi:cloud
    title: "Klimat"
    path: climate
    panel: true
    cards:
      - type: custom:layout-card
        max_columns: 5
        cards:
          - type: custom:bom-weather-card
            ...
            ...
```
