### ISSUE TITLE
Top and side margins look broken

### ISSUE THREAD

**Issue by ntompson** [thomasloven/lovelace-layout-card#70]
Hi,

Only just discovered this plugin and I love it. Unfortunately, though the margins seem to be out of whack: the top margin appears to be zero and side margins quite thin. This looks similar to a previous issue (#32).

My config:

```yaml
title: Heatpump
icon: 'mdi:fire'
badges: []
panel: true
cards:
- type: custom:layout-card
  max_columns: 3
  cards:
    # Heatpump status icon panel
    - type: glance
      entities:
        - entity: binary_sensor.hp_active
        - entity: binary_sensor.hp_hc1_pump
...
```

Top and side margins look wrong:

<img width="495" alt="Screen Shot 2020-04-29 at 11 48 34 am" src="https://user-images.githubusercontent.com/32885870/80554078-5f864900-8a0f-11ea-9021-00f1f2ac8aae.png">

Edit: I'm seeing this in Chrome (macOS) and Safari (iOS)
