### ISSUE TITLE
Custom element doesn't exist: layout-card.  type: 'custom:layout-card'

### ISSUE THREAD

**Issue by lecrote** [thomasloven/lovelace-layout-card#71]
I got this error that make me crazy.
I read the documentation and can't find what I'm doing wrong.
1- I create www/plugins directory
2- Download the raw layout-card.js to the directory
3- enable advance mode in config
4- put /plugins/layout-card.js in the ressources of lovelace ressources
5- here's the views example that I try
```
views:
  - badges: []
    cards:
      - type: 'custom:layout-card'
      - entities:
          - sensor.lm_q910_battery_level
          - sensor.lm_q910_geocoded_location
          - sensor.lm_q910_wifi_connection
        type: glance
      - break
      - entities:
          - sensor.lm_q910_battery_level
          - sensor.lm_q910_geocoded_location
          - sensor.lm_q910_wifi_connection
        type: glance
    path: home
    title: Home
```

I know, I need to read docs and I did more that 3 times but there's something that i should miss!

Thanks
