### ISSUE TITLE
Add column align capability

### ISSUE THREAD

**Issue by mniquette** [thomasloven/lovelace-layout-card#72]
Love the card. Here's an example of what I use for my views
```
title: Security
panel: true
cards:
  - type: custom:layout-card
    layout: vertical
    max_columns: 2
    cards:
      - !include security_alarm_card.yaml
      - !include security_status_card.yaml
      - break
      - !include security_sensors_card.yaml
```
This works great for any screen in portrait or landscape mode as well as for single column displays. What I would like to see, if possible, is in the case where two or more columns are present a command that would align the bottom edge of all the columns. The command could be presented like the current break command. The simplest solution would be to just elongate the last card of each shorter column to match the bottom of the longest column when the command is encountered. In the case of a single column display nothing happens. Thanks
