### ISSUE TITLE
Error when using markdown-card inside layout-card

### ISSUE THREAD

**Issue by hafffe** [thomasloven/lovelace-layout-card#74]
Hi, 
Noticed dev tools console was full of a error when playing around with lovelace,
it seems like layout-card doesn't play very well together with the markdown-card.
The error that occurs is `bootstrap:2 Uncaught (in promise) {code: "not_found", message: "Subscription not found."}`

Two examples, the first example generates the error

```
title: Test
icon: mdi:ab-testing
panel: true
path: test
cards:
  - type: custom:layout-card
    layout: vertical
    max_width: '100%'
    cards:
      - type: markdown
        content: |
          Hello

```

and this does not generate any error

```
title: Test
icon: mdi:ab-testing
panel: true
path: test
cards:
  - type: custom:layout-card
    layout: vertical
    max_width: '100%'
    cards:
      - type: entity
        entity: light.office
```
