### ISSUE TITLE
Wrapping input-select in horizontal layout layout-card causes flickering when opening dropdown on the bottom of the screen

### ISSUE THREAD

**Issue by matejdro** [thomasloven/lovelace-layout-card#78]
If there is input-select entity inside layout-card with horizontal layout on the bottom of the screen (so opening input-select dropdown would cause vertical scrollbar to appear), vertical scrollbar will start to appear and disappear, causing annoying flickering:

Video: https://gfycat.com/sereneblaringindianjackal

Example code:

```yaml
- cards:
  - entities:
      - entity: input_select.my_input_select
    show_header_toggle: false
    title: Selectt entity
    type: entities
layout: horizontal
type: 'custom:layout-card'
```

This is with Firefox 77.0.1.

if I remove layout-card wrapper, flickering stops. This is with https://github.com/thomasloven/lovelace-layout-card/commit/af99dbaf90887e6ce1c4eba6535c495a440c47bb.
