### ISSUE TITLE
After upgrading from 13 to 15, layout-card does not do 3 columns

### ISSUE THREAD

**Issue by shauder** [thomasloven/lovelace-layout-card#83]
I have layout-card in panel mode.  Before updating it would display 3 columns in the main panel layout-card. After I upgraded it only shows 2 columns now with lots of space on either side. If I change `max_columns` to 4, then it will display 3 columns. When I change it back to 3, it only shows 2.

I am using FireFox on Windows and macOS.

```yaml
# lovelace_gen
title: "Home"
path: "home"
panel: true
cards:
  - type: custom:layout-card
    max_columns: 3
    cards:
      {% for room in _global.rooms %}
      - type: vertical-stack
        cards:
          - type: markdown
            style: |
              ha-card {
                --paper-card-background-color: 'rgba(11, 11, 11, 0.00)';
                box-shadow: 2px 2px rgba(0,0,0,0.0);
              }
              h1 {
                font-size: 24px;
                font-weight: bold;
                font-family: Helvetica;
                letter-spacing: '0.01em';
                color: rgb(180, 225, 250);
              }
            content: |
              # {{ room | replace("_", " ") }}
          - type: custom:auto-entities
            card:
              type: custom:layout-card
              min_columns: 3
              max_columns: 3
              layout: horizontal
            filter:
              include:
                - entity_id: "light.{{ room | replace("_bedroom", "")  }}*"
                  sort:
                    method: name
                  options:
                    !include 
                    - ../templates/button.yaml
                    - entity: this.entity_id
                      button_type: color_light
                - entity_id: "climate.{{ room | replace("_bedroom", "")  }}*"
                  sort:
                    method: name
                  options:
                    !include 
                    - ../templates/button.yaml
                    - entity: this.entity_id
                      show_icon: false
                      button_type: thermostat
                - entity_id: "binary_sensor.contact_{{ room | replace("_bedroom", "")  }}*"
                  sort:
                    method: name
                  options:
                    !include 
                    - ../templates/button.yaml
                    - entity: this.entity_id
                      button_type: contact_sensor
                - entity_id: "binary_sensor.motion_{{ room | replace("_bedroom", "")  }}*"
                  sort:
                    method: name
                  options:
                    !include 
                    - ../templates/button.yaml
                    - entity: this.entity_id
                      button_type: motion_sensor
                - entity_id: "lock.{{ room | replace("_bedroom", "")  }}*"
                  sort:
                    method: name
                  options:
                    !include 
                    - ../templates/button.yaml
                    - entity: this.entity_id
                      button_type: lock
                - type: custom:button-card
                  color_type: blank-card
                  aspect_ratio: 1/1
                - type: custom:button-card
                  color_type: blank-card
                  aspect_ratio: 1/1
              exclude:
                - name: "{{ room | replace("_bedroom", "") | capitalize }}*"
                - name: "{{ room | replace("_room", "") | capitalize }}*"
          {% endfor %}
```
