### ISSUE TITLE
Conditional card creates a blank space and sometimes rearranges cards

### ISSUE THREAD

**Issue by rccoleman** [thomasloven/lovelace-layout-card#86]
Opening this as a new issue based on https://github.com/thomasloven/lovelace-layout-card/issues/5 because I don't want it to get buried in a closed issue.

I've started seeing the issue described in https://github.com/thomasloven/lovelace-layout-card/issues/5 when I added two conditional cards to an existing horizontal layout of 7 button cards.  Depending on the conditions, either 1 or none of the conditional cards should be visible, and I always end up with a blank space in the layout when one of them is visible and the other is not.  If neither is visible or both are visible, the layout is as-expected.  As above, you I get a "display: none" in the element picker:

<img width="627" alt="Screen Shot 2020-07-06 at 11 40 06 AM" src="https://user-images.githubusercontent.com/860888/86627655-874cdc80-bf7d-11ea-8195-a9b392e938e9.png">

Example:

<img width="964" alt="Screen Shot 2020-07-06 at 11 44 55 AM" src="https://user-images.githubusercontent.com/860888/86628056-2a9df180-bf7e-11ea-9dc1-f580402459bf.png">

Card snippet:

```
                # type: horizontal-stack
                type: custom:layout-card
                layout: horizontal
                min_columns: 9
                max_width: 150px
                min_height: 100px
                cards:
                - type: conditional
                  card:
                    type: "custom:button-card"
                    entity: sensor.landscape
                    template: badge_template_desktop
                    name: Landscape
                    icon: "mdi:pine-tree"
                    show_name: true
                    show_state: false
                    state:
                      - value: "0"
                        color: red
                      - value: "1"
                        color: green
                  conditions:
                    - entity: sensor.landscape
                      state_not: '2'
                - type: conditional
                  card:
                    type: "custom:button-card"
                    entity: sensor.recyling
                    template: badge_template_desktop
                    name: Recycling
                    icon: "mdi:recycle"
                    show_name: true
                    show_state: false
                    state:
                      - value: "0"
                        color: red
                      - value: "1"
                        color: green
                  conditions:
                    - entity: sensor.recycling
                      state_not: '2'
```

Changing the `min_columns:` to smaller values also seems to move the buttons around in unexpected ways - making it 5, 6, or 7 creates a new row (expected), but the icon directly below the blank space is rendered in the blank space, and the blank space ends up below:

<img width="733" alt="Screen Shot 2020-07-06 at 11 51 20 AM" src="https://user-images.githubusercontent.com/860888/86628639-07c00d00-bf7f-11ea-8bcd-64437f86f307.png">

Sometimes, the icons will effectively "rotate" in a single line, where the one at the end moves to the beginning, followed by a blank space, followed by the normal icons from there to the end.

A regular `horizontal-stack` displays the button correctly regardless of whether the conditional cards are visible, but it offers considerably less flexibility than card layout.

I'm using v16 of the layout card, the latest from HACS.
