### ISSUE TITLE
Lovelace dashboard doesn't show up until it is edited after Home Assistant upgrade

### ISSUE THREAD

**Issue by greyivy** [thomasloven/lovelace-layout-card#96]
When lovelace is initially loaded, it's blank. If I look in the DOM, I can find `Custom element doesn't exist: layout-card`. If I go to the menu and click "Edit Dashboard", everything works normally.

This only seems to be happening on certain pages.

**Comment by chriss158** [comment]
I have exactly the same problem since update to HA 0.116. 

I can reproduce the issue with this simple layout in panel mode:

```
cards:
  - entity: weather.home
    theme: Animated Weather Card
    type: weather-forecast
type: 'custom:layout-card'

```

I've cleared all cache data.
